return {
	ACTIONFAIL =
	{
		SHAVE =
		{
			AWAKEBEEFALO = "我 不 想 打 扰 它.",
			GENERIC = "我 还 不 能 刮！",
			NOBITS = "可 怜 的 秃 子..",
		},
		STORE =
		{
			GENERIC = "它 已 经 满 了.",
			NOTALLOWED = "这 个 不 能 放 进 去 .",
		},
		REPAIRBOAT = {
			GENERIC = "我 觉 得 它 没 有 问 题.",
		},
	},
	ACTIONFAIL_GENERIC = "我 做 不 到.",
	ANNOUNCE_ADVENTUREFAIL = "那 个 维 度 里 有 让 我 很 不 安 的 东 西. 我 必 须 要 再 试 一 次.",
	ANNOUNCE_BEES = "不 管 它 在 哪 儿 ，都 能 有 规 律 的 生 活.",
	ANNOUNCE_BOOMERANG = "哎 哟，这 是 我 的 物 理 极 限 ?",
	ANNOUNCE_CHARLIE = "在 哪？它 到 底 在 哪?!",
	ANNOUNCE_CHARLIE_ATTACK = "她 迫 使 我 离 开 这 个 世 界!!",
	ANNOUNCE_COLD = "太 冷 了!",
	ANNOUNCE_HOT = "我 抵 抗 不 了 了!",
	ANNOUNCE_CRAFTING_FAIL = "我 没 有 足 够 的 材 料.",
	ANNOUNCE_DEERCLOPS = "我 感 受 到 巨 大 的 怪 物 正 在 靠 近!",
	ANNOUNCE_DUSK = "我 想 睡 觉 了..",
	ANNOUNCE_EAT =
	{
		GENERIC = "这 个 世 界 上 的 食 物 独 一 无 二.",
		PAINFUL = "这 个 食 物 让 人 痛 苦...",
		SPOILED = "它 过 期 了.",
		STALE = "它 准 确 来 说 不 能 算 是 食 物.",
		INVALID = "我 能 吃 人，但 不 吃 这 个!",
	},
	ANNOUNCE_ENTER_DARK = "太 暗 了!",
	ANNOUNCE_ENTER_LIGHT = "现 在 我 能 看 到 点 光 线 了.",
	ANNOUNCE_FREEDOM = "最 后，我 可 以 在 家 里 休 息 一 下!",
	ANNOUNCE_HIGHRESEARCH = "学 无 止 境..",
	ANNOUNCE_HOUNDS = "猎 狗 来 了!",
	ANNOUNCE_SHARX = "大 白 鲨!",
	ANNOUNCE_HUNGRY = "是 时 候 吃 点 东 西 了.",
	ANNOUNCE_HUNT_BEAST_NEARBY = "我 感 觉 周 围 有 野 兽.",
	ANNOUNCE_HUNT_LOST_TRAIL = "踪 迹 消 失 了.",
	ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "地 面 太 泥 泞， 我 看 不 到 动 物 脚 印.",
	ANNOUNCE_INV_FULL = "我 拿 不 了 更 多 东 西",
	ANNOUNCE_KNOCKEDOUT = "欧，我 的 头!",
	ANNOUNCE_LOWRESEARCH = "我 从 那 没 学 到 什 么.",
	ANNOUNCE_MOSQUITOS = "传 染 疾 病 的 源 头.",
	ANNOUNCE_NODANGERSLEEP = "它 们 注 意 到 我 了，我 还 不 能 休 息.",
	ANNOUNCE_NODAYSLEEP = "恩，我 还 不 困 呢.",
	ANNOUNCE_NODAYSLEEP_CAVE = "恩，我 还 不 困 呢.",
	ANNOUNCE_NOHUNGERSLEEP = "我 饿 着 肚 子 时 候 不 想 睡 觉",
	ANNOUNCE_NOSLEEPONFIRE = "睡 在 这 似 乎 是 一 个 坏 主 意.",
	ANNOUNCE_NODANGERSIESTA = "它 们 注 意 到 我 了，我 不 能 睡 觉.",
	ANNOUNCE_NONIGHTSIESTA = "晚 上 是 睡 觉 的 时 间 而 不 是 午 休.",
	ANNOUNCE_NONIGHTSIESTA_CAVE = "我 不 觉 得 我 能 在 这 里 得 到 很 好 的 休 息.",
	ANNOUNCE_NOHUNGERSIESTA = "我 太 饿 了 不 想 午 休!",
	ANNOUNCE_NO_TRAP = "恩，这 很 容 易.",
	ANNOUNCE_PECKED = "哎 哟！你 啄 我?!",
	ANNOUNCE_QUAKE = "我 要 注 意 我 的 头.",
	ANNOUNCE_RESEARCH = "永 远 不 要 停 止 学 习!",
	ANNOUNCE_SHELTER = "啊，我 想 休 息 一 会.",
	ANNOUNCE_THORNS = "啊! 我 手 被 刺 痛 了!",
	ANNOUNCE_BURNT = "啊! 关 灯! 这 太 疯 狂 了!",
	ANNOUNCE_TORCH_OUT = "我 的 火 把 烧 完 了!",
	ANNOUNCE_TRAP_WENT_OFF = "哎 呀,",
	ANNOUNCE_UNIMPLEMENTED = "喔! 我 认 为 它 还 没 准 备 好.",
	ANNOUNCE_WORMHOLE = "可 怕 的 黑 洞! 我 不 想 再 试 一 次 了.",
	ANNOUNCE_CANFIX = "\n我 能 修 好 它.",
	ANNOUNCE_ACCOMPLISHMENT = "我 成 功 了 吗?",
	ANNOUNCE_ACCOMPLISHMENT_DONE = "好 吧，它 已 经 完 成 了.",	
	ANNOUNCE_INSUFFICIENTFERTILIZER = "这 棵 植 物 快 要 枯 萎 了. 它 需 要 一 些 肥 料.",
	ANNOUNCE_TOOL_SLIP = "啊! 这 很 危 险!",
	ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "哇, 这 是 完 全 防 电 的?",

	ANNOUNCE_DAMP = "恩, 它 湿 了!.",
	ANNOUNCE_WET = "我 的 衣 服 都 湿 了!",
	ANNOUNCE_WETTER = "我 全 身 都 湿 透 了!",
	ANNOUNCE_SOAKED = "我 的 身 体 如 此 沉 重!",
	
	ANNOUNCE_TREASURE = "我 现 在 是 一 名 寻 宝 者.",
	ANNOUNCE_MORETREASURE = "在 某 个 地 方 肯 定 还 有 宝 藏.",
	ANNOUNCE_OTHER_WORLD_TREASURE = "我 认 为 这 是 错 误 的 地 图.",
	ANNOUNCE_OTHER_WORLD_PLANT = "这 种 植 物 在 这 里 不 能 生 长.",
	
	ANNOUNCE_MESSAGEBOTTLE =
	{
		"这 消 息 都 模 糊 了，我 认 不 出 来 了.",
	},
	ANNOUNCE_VOLCANO_ERUPT = "这 真 是 一 场 大 喷 发!",
	ANNOUNCE_MAPWRAP_WARN = "这 里 有 怪 物 .",
	ANNOUNCE_MAPWRAP_LOSECONTROL = "好 多 雾...",
	ANNOUNCE_MAPWRAP_RETURN = "我 并 没 有 那 么 危 险.",
	ANNOUNCE_CRAB_ESCAPE = "它 消 失 了!",
	ANNOUNCE_TRAWL_FULL = "好 多 鱼 呀!",
	ANNOUNCE_BOAT_DAMAGED = "注 意 看 着 点 船.",
	ANNOUNCE_BOAT_SINKING = "哎 呀，这 可 不 妙.",
	ANNOUNCE_BOAT_SINKING_IMMINENT = "它 已 经 坏 了!",
	ANNOUNCE_WAVE_BOOST = "噢 耶! 冲 浪 时 间!",

	ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "我 闻 到 了 野 兽 的 味 道，咸 咸 的..!",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "我 找 不 到 气 泡.",
	ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "我 眼 睛 看 不 到 踪 迹 了.",
	
	BATTLECRY =
	{
		GENERIC = "我 要 赐 你 死 亡!",
		PIG = "哈! 我 踢 了 猪 一 下!",
		PREY = "我 要 抹 杀 你!",
		SPIDER = "我 会 取 出 你 的 心 脏!",
		SPIDER_WARRIOR = "嘿! 你 想 跑?",
	}, 
	COMBAT_QUIT =
	{
		GENERIC = "现 在 你 被 我 杀 了.",
		PIG = "这 正 是 我 想 做 的!",
		PREY = "你 比 我 还 弱.",
		SPIDER = "有 点 可 怕!",
		SPIDER_WARRIOR = "你 是 多 么 的 脆 弱!",
	},
	DESCRIBE =
	{
        GLOMMER = "嘿! 你 看 得 到 紫 外 线 吗?",
        GLOMMERFLOWER = 
        {
        	GENERIC = "大 王 花! 不 过 它 闻 起 来 没 什 么 味 道.",
        	DEAD = "我 很 奇 怪，这 东 西 闻 起 来 真 见 鬼.",
        },
        GLOMMERWINGS = "它 是 用 翅 膀 飘 着 吗?",
        GLOMMERFUEL = "真 讨 厌!",
        BELL = "也 许 我 不 该 把 这 个 放 在 大 门 上?",
        STATUEGLOMMER = 
        {	
        	GENERIC = "它 象 征 着 某 些 特 别 的 东 西.",
        	EMPTY = "我 感 受 到 上 面 仍 有 神 奇 的 力 量.",
    	},

		WEBBERSKULL = "可 怜 的 小 家 伙，他 应 该 举 行 一 场 合 适 的 葬 礼.",
		WORMLIGHT = "这 东 西 能 消 化 吗?",
		WORM =
		{
		    PLANT = "它 在 诱 惑 我.",
		    DIRT = "里 面 好 像 有 虫 子.",
		    WORM = "好 大 的 蠕 虫!",
		},
		MOLE =
		{
			HELD = "别 担 心，我 不 会 把 你 放 进 打 鼹 鼠 游 戏 里 的.",
			UNDERGROUND = "打 地 鼠 游 戏 的 现 实 版，呵 呵?",
			ABOVEGROUND = "打 它! 打 它!",
		},
		MOLEHILL = "矿 物 的 仓 库",
		MOLEHAT = "让 我 们 用 鼹 鼠 的 视 角 来 观 看.",

		EEL = "它 比 看 起 来 更...",
		EEL_COOKED = "闻 起 来 真 香!",
		UNAGI = "寿司?",
		EYETURRET = "多 奇 怪 的 炮 塔!",
		EYETURRET_ITEM = "我 会 很 小 心 地 放 置 它.",
		MINOTAURHORN = "还 没 有 石 头 硬，或 许 我 可 以 吃 吃 看.",
		MINOTAURCHEST = "典 型 的 副 本 BOSS 奖 励, 呵 呵?",
		THULECITE_PIECES = "一 堆 神 奇 的 东 西.",
		POND_ALGAE = "天 然 的 海 藻 池 塘.",
		GREENSTAFF = "这 东 西 看 起 来 不 用 损 耗 工 具 就 可 以 拆 卸 了 呢.",
		POTTEDFERN = "没 有 花 的 植 物，只 会 产 生 孢 子.",

		THULECITE = "它 渴 望 别 人 的 恐 惧.",
		ARMORRUINS = "它 在 虚 空 中 微 弱 的 发 着 光.",
		RUINS_BAT = "它 可 以 在 任 何 时 候 发 出 噩 梦 般 的 力 量.",
		RUINSHAT = "破 损 的 国 王 皇 冠.",
		NIGHTMARE_TIMEPIECE =
		{
		CALM = "一 切 都 平 静 了.",
		WARN = "黑 暗 变 得 更 浓 了.",
		WAXING = "环 境 里 充 斥 这 噩 梦 般 的 景 象!",
		WANING = "我 能 感 受 到 神 奇 的 力 量.",
		STEADY = "它 开 始 失 去 它 的 力 量.",
		DAWN = "它 现 在 变 暗 了，但 还 没 有 消 失.",
		NOMAGIC = "这 里 没 有 魔 力.",
		},
		BISHOP_NIGHTMARE = "一 个 破 损 的 主 教.",
		ROOK_NIGHTMARE = "它 是 有 感 情 的，它 现 在 很 生 气.",
		KNIGHT_NIGHTMARE = "骑 士 的 噩 梦.",
		MINOTAUR = "我 觉 的 它 是 牛 头 人.",
		SPIDER_DROPPER = "长 着 白 胡 子 的 蜘 蛛!",
		NIGHTMARELIGHT = "我 在 里 面 看 到 了 可 怕 的 噩 梦.",
		NIGHTSTICK = "湿 润 后 将 变 成 最 强.",
		GREENGEM = "这 象 征 着 创 造 与 毁 灭.",
		RELIC = "这 应 该 被 展 出.",
		RUINS_RUBBLE = "它 可 以 被 修 复.",
		MULTITOOL_AXE_PICKAXE = "看 起 来 像 是 斧 和 镐 的 合 体.",
		ORANGESTAFF = "跟 我 伞 的 功 能一 样. 真 没 用!",
		YELLOWAMULET = "它 会 发 出 耀 眼 的 光 芒.",
		GREENAMULET = "它 能 从 虚 无 中 获 取 材 料.",
		SLURPERPELT = "好 脏.",	

		SLURPER = "它 是 单 细 胞 生 物 还 是 某 个 东 西?",
		SLURPER_PELT = "好 脏.",
		ARMORSLURPER = "能 够 有 效 利 用, 但 是 很 不 卫 生.",
		ORANGEAMULET = "这 有 什 么 用?",
		YELLOWSTAFF = "它 可 以 从 行 星 上 吸 取 光.",
		YELLOWGEM = "这 象 征 着 宇 宙 中 的 行 星.",
		ORANGEGEM = "这 象 征 着 人 类 的 欲 望.",
		TELEBASE = 
		{
			VALID = "能 量 在 上 面 流 淌.",
			GEMS = "它 需 要 更 多 的 紫 宝 石.",
		},
		GEMSOCKET = 
		{
			VALID = "这 里 设 置 坐 标 的 传 输.",
			GEMS = "它 需 要 一 个 紫 宝 石.",
		},
		STAFFLIGHT = "有 发 出 神 奇 魔 法 的 情 况.",
	
        ANCIENT_ALTAR = "它 们 一 定 生 活 在 高 度 发 达 文 明 中.",

        ANCIENT_ALTAR_BROKEN = "破 碎 的 祭 坛，我 可 以 用 原 料 修 复 它.",

        ANCIENT_STATUE = "虚 荣.",

        LICHEN = "发 光 的 共 生 体",
		CUTLICHEN = "这 会 腐 烂 的 很 快.",

		CAVE_BANANA = "它 的 DNA 结 构 和 人 类 相 似.",
		CAVE_BANANA_COOKED = "温 暖 又 好 吃!",
		CAVE_BANANA_TREE = "它 不 是 一 个 热 带 植 物 吗?",
		ROCKY = "它 们 的 肌 肉 被 坚 硬 的 石 头 保 护 着.",
		
		COMPASS =
		{
			GENERIC="这 上 面 没 有 使 用 说 明.",
			N = "北",
			S = "南",
			E = "东",
			W = "西",
			NE = "东 北",
			SE = "东 南",
			NW = "西 北",
			SW = "西 南",
		},

		NIGHTMARE_TIMEPIECE =
		{
			WAXING = "它 们 的 尖 叫 声 像 浪 花 一 样 汹 涌.",
			STEADY = "它 们 就 在 我 们 周 围.",
			WANING = "他 们 开 始 蔓 延",
			DAWN = "它 们 开 始 变 得 暗 淡.",
			WARN = "它 们 来 了.",
			CALM = "它 们 离 开 了.",
			NOMAGIC = "我 们 周 围 已 经 没 有 魔 力 了.",
		},

		HOUNDSTOOTH="又 硬 又 尖 锐，很 有 用.",
		ARMORSNURTLESHELL="这 个 最 终 也 会 被 打 破.",
		BAT="夜 间 的 哺 乳 动 物.",
		BATBAT = "为 什 么 成 分 里 面 没 有 它 们 的 牙 齿 呢?",
		BATWING="上 面 好 多 毛，我 不 喜 欢 这 个.",
		BATWING_COOKED="比 起 生 的 好 很 多.",
		BEDROLL_FURRY="好 温 馨.",
		BUNNYMAN="它 们 恨 我 吗..?",
		FLOWER_CAVE="这 可 不 是 LED 灯.",
		FLOWER_CAVE_DOUBLE="这 可 不 是 LED 灯.",
		FLOWER_CAVE_TRIPLE="这 可 不 是 LED 灯.",
		GUANO="太 臭 了.",
		LANTERN="这 有 点 重.",
		LIGHTBULB="...可 食 用 的 灯 泡.",
		MANRABBIT_TAIL="毛 茸 茸 的",
		MUSHTREE_TALL  ="这 比 普 通 的 树 还 高!.",
		MUSHTREE_MEDIUM="跟 MC 里 面 的 很 不 一 样.",
		MUSHTREE_SMALL ="神 奇 的 绿 色 蘑 菇 树.",
		RABBITHOUSE=
		{
			GENERIC = "它 们 真 的 喜 欢 胡 萝 卜 吗?",
			BURNT = "它 在 燃 烧.",
		},
		SLURTLE="它 在 寻 找 矿 藏.",
		SLURTLE_SHELLPIECES="看 起 来 是 花 盆 的 好 材 料.",
		SLURTLEHAT="它 和 头 部 贴 的 好 紧.",
		SLURTLEHOLE="怎 么 这 么 尖 锐?",
		SLURTLESLIME="容 易 爆 炸 的 黏 质 物.",
		SNURTLE="它 看 起 来 一 点 都 不 积 极.",
		SPIDER_HIDER="它 们 的 皮 肤 如 此 密 集!",
		SPIDER_SPITTER="普 通 的 物 理 伤 害 怪 物.",
		SPIDERHOLE="看 起 来 像 蜘 蛛 巢 穴.",
		STALAGMITE="它 们 确 实 在 生 长, 虽 然 他 们 不 是 有 机 体.",
		STALAGMITE_FULL="似 乎 它 们 完 全 长 大 了.",
		STALAGMITE_LOW="它 们 确 实 在 生 长, 虽 然 它 们 不 是 有 机 体.",
		STALAGMITE_MED="它 们 确 实 在 生 长, 虽 然 它 们 不 是 有 机 体.",
		STALAGMITE_TALL="它 们 确 实 在 生 长, 虽 然 它 们 不 是 有 机 体.",
		STALAGMITE_TALL_FULL="似 乎 它 们 完 全 长 大 了.",
		STALAGMITE_TALL_LOW="它 们 确 实 在 生 长, 虽 然 它 们 不 是 有 机 体.",
		STALAGMITE_TALL_MED="它 们 确 实 在 生 长, 虽 然 它 们 不 是 有 机 体.",

		TURF_CARPETFLOOR = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_CHECKERFLOOR = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_DIRT = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_FOREST = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_GRASS = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_MARSH = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_ROAD = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_ROCKY = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_SAVANNA = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_WOODFLOOR = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",

		TURF_CAVE="从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_FUNGUS="从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_SINKHOLE="从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_UNDERROCK="从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_MUD="从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",

		TURF_DECIDUOUS = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURD_SANDY = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",
		TURF_BADLANDS = "从 此 之 后 它 是 一 个 物 品. 我 可 以 拿 着 它.",

		POWCAKE = "我 觉 得 它 没 有 营 养.",
        CAVE_ENTRANCE = 
        {
            GENERIC="有 人 故 意 把 它 堵 上 了.",
            OPEN = "我 可 以 下 去 看 看.",
        },
        CAVE_EXIT = "我 不 觉 得 我 有 捆 过 一 根 绳 子.",
		MAXWELLPHONOGRAPH = "它 在 折 磨 他.",
		BOOMERANG = "说 实 话，这 个 真 的 很 难 控 制.",
		PIGGUARD = "愚 蠢 的 狂 热 者.",
		ABIGAIL = "谁 把 你 变 成 不 死 族?",
		ADVENTURE_PORTAL = "这 是 我 必 须 要 去 做 的.",
		AMULET = "这 给 了 我 额 外 的 生 命.",
		ANIMAL_TRACK = "野 兽 留 下 的 痕 迹.",
		ARMORGRASS = "我 很 担 忧 它 是 否 真 的 可 以 保 护 我.",
		ARMORMARBLE = "真 的，它 很 沉 重.",
		ARMORWOOD = "我 真 的 不 想 用 它 和 火 打 架.",
		ARMOR_SANITY = "看 起 来 更 像 一 个 盾.",
		ASH =
		{
			GENERIC = "每 一 个 凡 人 的 终 点.",
			REMAINS_GLOMMERFLOWER = "哦，它 并 没 有 消 失.",
			REMAINS_EYE_BONE = "哦，它 并 没 有 消 失.",
			REMAINS_THINGIE = "哦，它 并 没 有 消 失.",
		},
		AXE = "这 比 剑 更 不 耐 用.",
		BABYBEEFALO = "看 那 些 空 洞 的 眼 睛!",
		BACKPACK = "生 存 的 必 需 品 之 一.",
		BACONEGGS = "丰 富 的 蛋 白 质",
		BANDAGE = "我 不 认 为 这 对 我 的 皮 肤 有 好 处.",
		BASALT = "一 块 岩 石.",
		BATBAT = "为 什 么 它 的 成 分 中 不 包 含 它 的 牙 齿?",
		BEARDHAIR = "肮 脏 的 胡 须",
		BEARGER = "好 大 一 只 熊 獾!",
		BEARGERVEST = "我 担 心 我 要 冬 眠 了.",
		ICEPACK = "天 然 泡 沫",
		BEARGER_FUR = "它 富 含 高 脂 肪.",
		BEDROLL_STRAW = "有 点 粗 糙.",
		BEE =
		{
			GENERIC = "小 心 蜜 蜂!",
			HELD = "蜜 蜂，冷 静!",
		},
		BEEBOX =
		{
			FULLHONEY = "那 气 味 诱 惑 着 我!",
			GENERIC = "小 心 蜜 蜂!",
			NOHONEY = "空 空 的.",
			SOMEHONEY = "那 气 味 诱 惑 着 我!",
			BURNT = "等 一 下，蜂 蜜 是 易 燃 的?",
		},
		BEEFALO =
		{
			FOLLOWER = "我 是 牧 牛 者 吗?.",
			GENERIC = "看 看 那 张 丑 爆 了 的 脸!",
			NAKED = "抱 歉 一 直 看 着 你.",
			SLEEPING = "那 是 打 鼾 的 声 音?",
		},
		BEEFALOHAT = "戴 着 这 顶 帽 子，牛 哥 就 再 也 不 会 怀 疑 我 了.",
		BEEFALOWOOL = "没 有 我 想 象 中 的 那 么 难 闻.",
		BEEHAT = "上 面 的 网 格 比 蜂 刺 还 要 小.",
		BEEHIVE = "我 想 要 蜂 蜜.",
		BEEMINE = "小 心 轻 放",
		BEEMINE_MAXWELL = "我 觉 得 里 面 可 能 有 蚊 子.",
		BERRIES = "Ardisia crenata.",
		BERRIES_COOKED = "粘 粘 的.",
		BERRYBUSH =
		{
			BARREN = "我 觉 得 它 需 要 浇 灌.",
			WITHERED = "炎 热 使 它 枯 萎.",
			GENERIC = "Ardisia crenata.",
			PICKED = "它 们 将 在 3 - 5 天 内 重 新 长 好.",
		},
		BIGFOOT = "看 看 它 头 上 的 大 脑!",
		BIRDCAGE =
		{
			GENERIC = "我 要 放 只 鸟 进 去.",
			OCCUPIED = "它 知 道 逃 不 出 去 了.",
			SLEEPING = "它 睡 着 了.",
		},
		BIRDTRAP = "它 们 会 停 在 这 里 吗?",
		BIRD_EGG = "它 比 我 想 象 中 的 要 小 一 点.",
		BIRD_EGG_COOKED = "看 起 来 很 美 味.",
		BISHOP = "似 乎 它 们 在 等 待 着 什 么.",
		BLOWDART_FIRE = "它 能 使 目 标 着 火.",
		BLOWDART_SLEEP = "我 要 当 心 别 把 它 吸 进 来.",
		BLOWDART_PIPE = "我 是 一 个 忍 者!",
		BLUEAMULET = "它 可 以 吸 热.",
		BLUEGEM = "它 象 征 着 寒 冷.",
		BLUEPRINT = "我 不 知 道 它 是 怎 么 起 作 用 的.",
		BELL_BLUEPRINT = "它 的 成 分 非 常 可 疑",
		BLUE_CAP = "长 长 的 蓝 色 蘑 菇.",
		BLUE_CAP_COOKED = "味 道 甜 美.",
		BLUE_MUSHROOM =
		{
			GENERIC = "它 会 在 夜 晚 长 出 来.",
			INGROUND = "我 拔 不 出 来.",
			PICKED = "下 雨 后 会 重 新 长 出 来 的.",
		},
		BOARDS = "平 的 木 板.",
		BOAT = "漂 亮 的 船.",
		BONESHARD = "碎 骨.",
		BONESTEW = "哦, 碳 酸 钙.",
		BUGNET = "捕 捉 虫 子 的 工 具.",
		BUSHHAT = "我 希 望 这 能 起 点 作 用.",
		BUTTER = "黄 油 来 自 蝴 蝶.",
		BUTTERFLY =
		{
			GENERIC = "蝴 蝶，飞 舞 着.",
			HELD = "喔，真 可 怜, 我 不 想 杀 你.",
		},
		BUTTERFLYMUFFIN = "它 的 样 子 使 我 痛 苦.",
		BUTTERFLYWINGS = "现 在 我 把 你 杀 了.",
		BUZZARD = "它 们 在 寻 找 垃 圾.",
		CACTUS = 
		{
			GENERIC = "它 们 的 叶 子 是 非 常 薄.",
			PICKED = "三 天 后 会 重 新 长 出 来.",
		},
		CACTUS_MEAT_COOKED = "烤...果 汁 !",
		CACTUS_MEAT = "多 汁 ，尖 尖 的.",
		CACTUS_FLOWER = "它 是 沙 漠 中 的 美 丽 风 景.",

		COLDFIRE =
		{
			EMBERS = "它 快 熄 灭 了",
			GENERIC = "相 反 的 火 焰. 好 有 趣.",
			HIGH = "它 吸 收 了 这 里 的 大 部 分 热 量.",
			LOW = "它 依 旧 美 丽.",
			NORMAL = "相 反 的 火 焰。有 趣.",
			OUT = "好 吧 它 熄 灭 了.",
		},
		CAMPFIRE =
		{
			EMBERS = "它 快 要 熄 灭 了.",
			GENERIC = "为 什 么 这 里 的 夜 晚 这 么 黑?",
			HIGH = "我 需 要 清 除 这 里 的 可 燃 物.",
			LOW = "最 好 加 点 燃 料.",
			NORMAL = "常 见 的 篝 火.",
			OUT = "好 吧，它 熄 灭 了.",
		},
		CANE = "它 有 什 么 用 呢?",
		CATCOON = "它 正 无 聊 着 呢.",
		CATCOONDEN = 
		{
			GENERIC = "这个 树 墩 是 谁 做 的?.",
			EMPTY = "里 面 空 荡 荡 的.",
		},
		CATCOONHAT = "我 觉 得 这 薄 了 点.",
		COONTAIL = "毛 茸 茸 的.",
		CARROT = "这 是 胡 萝 卜.",
		CARROT_COOKED = "对 夜 盲 症 来 说 这 可 是 好 食 物.",
		CARROT_PLANTED = "我 可 以 把 它 拔 出 来.",
		CARROT_SEEDS = "胡 萝 卜 的 种 子.",
		WATERMELON_SEEDS = "西 瓜 种 子.",
		CAVE_FERN = "一 种 蕨 类 植 物.",
		CHARCOAL = "男 人 的 心.",
        CHESSJUNK1 = "破 烂 发 条.",
        CHESSJUNK2 = "破 烂 发 条.",
        CHESSJUNK3 = "破 烂 发 条.",
		CHESTER = "笨 蛋，别 流 口 水.",
		CHESTER_EYEBONE =
		{
			GENERIC = "它 看 着 我 呢.",
			WAITING = "它 在 一 天 之 后 会 回 来 的.",
		},
		COOKEDMANDRAKE = "为 什 么 你 长 着 一 张 死 人 脸?!",
		COOKEDMEAT = "大 部 分 的 熟 肉 都 会 显 示 为 牛 排.",
		COOKEDMONSTERMEAT = "它 几 乎 没 有 刺.",
		COOKEDSMALLMEAT = "就 是 这 样.",
		COOKPOT =
		{
			COOKING_LONG = "这 得 花 一 点 时 间.",
			COOKING_SHORT = "就 快 好 了.",
			DONE = "做 好 了，我 可 以 品 尝 了.",
			EMPTY = "我 可 以 用 它 烹 饪 食 物.",
			BURNT = "锅 自 己 被 煮 了",
		},
		CORN = "玉 米. 只 要 一 半 能 用 来 吃.",
		CORN_COOKED = "烤 过 的 玉 米.. 我 的 意 思 是 爆 米 花!",
		CORN_SEEDS = "玉 米 种 子.",
		CROW =
		{
			GENERIC = "阿 空?",
			HELD = "我 抓 到 一 只 阿 空.",
		},
		CUTGRASS = "制 造 材 料.",
		CUTREEDS = "制 造 材 料.",
		CUTSTONE = "建 筑 材 料.",
		DEADLYFEAST = "用 于 自 杀",
		DEERCLOPS = "巨 人 的 一 只 眼 睛",
		DEERCLOPS_EYEBALL = "一点 都 不 血 腥.",
		EYEBRELLAHAT =	"有 点 吓 人.",
		DEPLETED_GRASS =
		{
			GENERIC = "需 要 浇 灌.",
		},
		DEVTOOL = "你 是 一 个 开 发 人 员 吗?",
		DEVTOOL_NODEV = "这 是 做 什 么 的?",
		DIRTPILE = "留 下 了 某 些 线 索.",
		DIVININGROD =
		{
			COLD = "周 围 没 什 么 东 西",
			GENERIC = "为 了 找 寻 某 种 '东 西'.",
			HOT = "你 的 屏 幕 内 有 东 西!",
			WARM = "喔, 它 有 反 应 了!",
			WARMER = "我 觉 得 东 西 就 在 这 里.",
		},
		DIVININGRODBASE =
		{
			GENERIC = "它 链 接 到 另 一 个 世 界.",
			READY = "我 需 要 插 入 我 的 魔 杖.",
			UNLOCKED = "我 想 看 看 世 界 之 后 有 什 么..",
		},
		DIVININGRODSTART = "我 要 把 它 拿 起 来.",
		DRAGONFLY = "这 个 生 物 让 我 很 困 惑.",
		ARMORDRAGONFLY = "我 觉 得 它 比 以 前 那 个 更 柔 软 一 些.",
		DRAGON_SCALES = "这 是 一 只 苍 蝇 的 鳞 片!",
		DRAGONFLYCHEST = "我 要 放 点 特 别 的 东 西 进 去.",
		LAVASPIT = 
		{
			HOT = "我 想 这 应 该 低 于 300°C.",
			COOL = "它 已 经 冷 却 了.",
		},
		DRAGONFRUIT = "这 是 火 龙 果，对 女 生 很 有 好 处.",
		DRAGONFRUIT_COOKED = "多 么 健 康 的 食 品!",
		DRAGONFRUIT_SEEDS = "火 龙 果 种 子.",
		DRAGONPIE = "比 以 前 更 健 康.",
		DRUMSTICK = "好 吃!",
		DRUMSTICK_COOKED = "鸡 腿!!",
		DUG_BERRYBUSH = "我 应 该 种 这 个.",
		DUG_GRASS = "我 应 该 种 这 个.",
		DUG_MARSH_BUSH = "我 应 该 种 这 个.",
		DUG_SAPLING = "我 应 该 种 这 个.",
		DURIAN = "榴 莲. 刺 激 性 的 食 物.",
		DURIAN_COOKED = "额, 这 不 是 个 好 主 意.",
		DURIAN_SEEDS = "榴 莲 种 子.",
		EARMUFFSHAT = "好 柔 软!",
		EGGPLANT = "茄 子，多 年 生 植 物.",
		EGGPLANT_COOKED = "我 不 想 单 独 吃 这 个.",
		EGGPLANT_SEEDS = "茄 子 种 子.",
		DECIDUOUSTREE = 
		{
			BURNING = "燃 烧.",
			BURNT = "它 烧 掉 了.",
			CHOPPED = "太 小 了，不 能 用 来 休 息.",
			POISON = "它 是 个 怪 物 吗?",
			GENERIC = "那 是 一 棵 落 叶 树。它 长 大 后 会 结 满 果 实.",
		},
		ACORN = 
		{
		    GENERIC = "树 种 子.",
		    PLANTED = "它 会 长 成 一 棵 树.",
		},
		ACORN_COOKED = "我 喜 欢 它 的 味 道.",
		BIRCHNUTDRAKE = "恶 魔 的 爪 牙.",
		EVERGREEN =
		{
			BURNING = "燃 烧.",
			BURNT = "它 烧 掉 了.",
			CHOPPED = "它 太 小 了，不 能 用 来 休 息.",
			GENERIC = "这 是 一 棵 树.",
		},
		EVERGREEN_SPARSE =
		{
			BURNING = "燃 烧.",
			BURNT = "它 烧 掉 了.",
			CHOPPED = "它 太 小 了，不 能 用 来 休 息.",
			GENERIC = "它 们 不 会 离 开 它 们 的 幼 体.",
		},
		EYEPLANT = "我 觉 得 我 被 注 视 着.",
		FARMPLOT =
		{
			GENERIC = "我 可 以 种 植 植 物.",
			GROWING = "她 正 在 生 长!",
			NEEDSFERTILIZER = "我 觉 得 它 需 要 浇 灌.",
			BURNT = "它 烧 着 了.",
		},
		FEATHERHAT = "它 们 会 把 我 当 成 同 伴.",
		FEATHER_CROW = "阿 空 的 羽 毛.",
		FEATHER_ROBIN = "红 雀 羽 毛.",
		FEATHER_ROBIN_WINTER = "雪 雀 羽 毛.",
		FEM_PUPPET = "",
		FIREFLIES =
		{
			GENERIC = "萤 火 虫，黑 夜 中 的 远 征 军",
			HELD = "它 们 为 了 繁 育 而 发 光.",
		},
		FIREHOUND = "不 要 让 它 死 在 建 筑 旁 边.",
		FIREPIT =
		{
			EMBERS = "它 快 要 熄 灭 了.",
			GENERIC = "好 无 趣.",
			HIGH = "更 温 暖 了.",
			LOW = "最 好 再 加 点 燃 料.",
			NORMAL = "接 下 来 要 干 嘛 呢?",
			OUT = "好 吧，它 熄 灭 了.",
		},
		COLDFIREPIT =
		{
			EMBERS = "它 快 要 熄 灭 了.",
			GENERIC = "好 凉 爽.",
			HIGH = "嗯，那 至 少 是 美 丽 的.",
			LOW = "最 好 再 加 点 燃 料.",
			NORMAL = "好 不 现 实 呀.",
			OUT = "好 吧，它 熄 灭 了.",
		},
		FIRESTAFF = "火 焰 巫 师.",
		FIRESUPPRESSOR = 
		{	
			ON = "冰 的 来 源 是 什 么 呢?",
			OFF = "它 被 关 闭 了.",
			LOWFUEL = "最 好 再 加 点 燃 料.",
		},
		
		FISH = "看 起 来 好 丑.",
		FISHINGROD = "好 传 统 呀!",
		FISHSTICKS = "依 旧 是 鱼 肉!",
		FISHTACOS = "鱼 卷.",
		FISH_COOKED = "这 才 像 食 物.",
		FLINT = "用 来 制 造 尖 锐 工 具 很 有 用.",
		FLOWER = "麦 冬、薰 衣 草、牛 膝、风 铃..美 丽 的..美 丽 的.",
		FLOWERHAT = "看 起 来 好 变 扭!",
		FLOWER_EVIL = "看 起 来 很 漂 亮，但 它 会 损 耗 灵 魂.",
		FOLIAGE = "紫 色 的，我 很 喜 欢.",
		FOOTBALLHAT = "有 点 闷 热，但 很 牢 固.",
		FROG =
		{
			DEAD = "你 应 该 呆 在 井 里.",
			GENERIC = "有 点 可 怕. 一 点 都 不 像 青 蛙 子.",
			SLEEPING = "它 睡 觉 的 时 候 也 睁 着 眼 睛 吗?",
		},
		FROGGLEBUNWICH = "希 望 会 好 吃...!",
		FROGLEGS = "是 时 候 电 击 一 下 了 ?",
		FROGLEGS_COOKED = "比 起 电 击 这 样 更 好.",
		FRUITMEDLEY = "多 么 新 鲜!",
		GEARS = "这 个 科 学 机 器 真 是 让 人 难 以 理 解，它 有 什 么 用 呢?",
		GHOST = "你 是 永 生 的.",
		GOLDENAXE = "这 金 斧 头 比 石 斧 头 耐 用 多 了.",
		GOLDENPICKAXE = "我 觉 得 不 能 拿 这 个 来 开 采 钻 石?",
		GOLDENPITCHFORK = "为 什 么 我 还 想 做 一 个 金 草 叉 呢?",
		GOLDENSHOVEL = "劳 动 最 光 荣.",
		GOLDNUGGET = "似 乎 比 石 头 更 硬.",
		GRASS =
		{
			BARREN = "它 需 要 肥 料.",
			WITHERED = "它 因 热 而 枯 萎.",
			BURNING = "这 就 是 为 什 么 它 被 用 作 燃 料 的 原 因",
			GENERIC = "这 是 一 簇 草.",
			PICKED = "它 会 在 它 最 繁 茂 的 时 候 被 割  下 来 .",
		},
		GREEN_CAP = "我 觉 得 它 应 该 没 有 毒 性.",
		GREEN_CAP_COOKED = "咸 的!",
		GREEN_MUSHROOM =
		{
			GENERIC = "这 是 一 颗 绿 蘑 菇.",
			INGROUND = "它 会 在 黄 昏 的 时 候 冒 出 来.",
			PICKED = "两 天 之 后 它 会 再 生 出 来.",
		},
		GUNPOWDER = "是 时 候 来 一 场 烟 花 表 演 了!",
		HAMBAT = "这 武 器 好 不 方 便.",
		HAMMER = "这 地 方 有 鼹 鼠 吗?",
		HEALINGSALVE = "看 起 来 很 苦.",
		HEATROCK =
		{
			FROZEN = "和 琪 露 诺 一 样 冰 冷!",
			COLD = "冷 如 Letty.",
			GENERIC = "我 可 以 控 制 它 的 温 度.",
			WARM = "很 温 暖",
			HOT = "跟 阿 空 一 样 火 热!",
		},
		HOME = "一 定 有 人 住 在 这 里.",
		HOMESIGN = 
		{
			GENERIC = "它 说 '你 在 这' .",
			BURNT = "它 说... 我 看 不 清.",
		},
		HONEY = "看 起 来 好 甜",
		HONEYCOMB = "它 比 我 想 象 的 要 高.",
		HONEYHAM = "甜 甜 的, 黏 黏 的 肉!",
		HONEYNUGGETS = "我 亲 自 做 的!",
		HORN = "它 们 是 从 喇 叭 发 出 的 声 音?!",
		HOUND = "它 是 如 此 有 侵 略 性!",
		HOUNDBONE = "好 可 怕.",
		HOUNDMOUND = "那 是 猎 犬 的 巢 穴.",
		ICEBOX = "它 需 要 齿 轮，但 是 装 到 哪 去 了?",
		ICEHAT = "又 重 又 湿. 但 是 它 可 以 隔 绝 高 温.",
		ICEHOUND = "它 们 的 心 中 充 满 了 寒 冰.",
		INSANITYROCK =
		{
			ACTIVE = "在 魔 力 的 加  持 下 它 非 常 的 硬.",
			INACTIVE = "一 个 有 生 命 的 魔 法 石.",
		},
		JAMMYPRESERVES = "又 甜 又 黏.",
		KABOBS = "中 亚 的 传 统 食 品.",
		KILLERBEE =
		{
			GENERIC = "它 们 想 要 攻 击 别 的 事 物.",
			HELD = "给 我 冷 静.",
		},
		KNIGHT = "将,军.",
		KOALEFANT_SUMMER = "杂 交 的.. 生 物.",
		KOALEFANT_WINTER = "杂 交 的.. 生 物.",
		KRAMPUS = "它 好 像 偷 了 我 的 材 料.",
		KRAMPUS_SACK = "存 储 量 真 大。我 喜 欢 它.",
		LEIF = "这 是 个 怪 物 吗?",
		LEIF_SPARSE = "这 是 个 怪 物 吗?",
		LIGHTNING_ROD =
		{
			CHARGED = "好 强 的 力 量!",
			GENERIC = "安 全 第 一!",
		},
		LIGHTNINGGOAT = 
		{
			GENERIC = "你 想 让 我 想 起 了 模 拟 山 羊 游 戏.",
			CHARGED = "不 要 把 事 情 搞 得 一 团 糟!",
		},
		LIGHTNINGGOATHORN = "这 可 以 用 来 做 避 雷 针 吗?",
		GOATMILK = "这 是 一 种 碳 酸 饮 料.",
		LITTLE_WALRUS = "它 在 努 力 的 学 习.",
		LIVINGLOG = "你 被 诅 咒 过 吗?",
		LOCKEDWES = "它 似 乎 不 能 说 话，所 以 我 没 有 注 意 到 它.",
		LOG =
		{
			BURNING = "燃 烧",
			GENERIC = "这 是 一 个 木 头，典 型 的 资 源 生 存 游 戏.",
		},
		LUREPLANT = "它 最 终 要 做 什 么?",
		LUREPLANTBULB = "它 是 如 此 凶 狠.",
		MALE_PUPPET = "",
		MANDRAKE =
		{
			DEAD = "好 吧，它 看 起 来 更 像 人 参.",
			GENERIC = "曼 德 拉 草.",
			PICKED = ".....",
		},
		MANDRAKESOUP = "最 好 的 回 血 食 物!",
		MANDRAKE_COOKED = "为 什 么 它 看 起 来 像 胡 萝 卜?",
		MARBLE = "石 灰 石 结 晶.",
		MARBLEPILLAR = "离 子 柱.",
		MARBLETREE = "看 起 来 像 冰 激 凌.",
		MARSH_BUSH =
		{
			BURNING = "燃 烧",
			GENERIC = "这 又 不 是 玫 瑰，它 为 什 么 会 有 刺 呢!",
			PICKED = "啊，好 痛",
		},
		MARSH_PLANT = "它 们 在 被 烧 毁 后 还 会 再 生.",
		MARSH_TREE =
		{
			BURNING = "燃 烧",
			BURNT = "它 烧 掉 了.",
			CHOPPED = "我 要 把 刺 都 砍 掉.",
			GENERIC = "畸 形 的 树.",
		},
		MAXWELL = "他 在 那 里!",
		MAXWELLHEAD = "",
		MAXWELLLIGHT = "它 们 的 来 源 不 为 人 知",
		MAXWELLLOCK = "你 的 命 运 在 我 的 手 上.",
		MAXWELLTHRONE = "别 担 心.我 会 释 放 你 的 ，永 远.",
		MEAT = "生 吃 它 我 也 不 会 损 失 心 智.",
		MEATBALLS = "真 的, 做 这 个 的 食 谱 是 什 么?",
		MEATRACK =
		{
			DONE = "完 成 了",
			DRYING = "这 得 花 点 时 间 才 能 好.",
			DRYINGINRAIN = "下 雨 的 时 候 它 不 能 干 燥.",
			GENERIC = "保 存 食 物 的 好 方 法 .",
			BURNT = "烧 坏 了.",
		},
		MEAT_DRIED = "比 我 想 象 中 的 还 要 黑.",
		MERM = "这 真 可 怕!",
		MERMHEAD = 
		{
			GENERIC = "又 脏, 又 吓 人，真 糟 糕!",
			BURNT = "还 是 好 恶 心.",
		},
		MERMHOUSE = 
		{
			GENERIC = "谁 住 在 这 个 废 弃 屋 子 里 呢?",
			BURNT = "真 的. 烧 了 好.",
		},
		MINERHAT = "这 可 以 延 长 我 的 活 动 时 间.",
		MONKEY = "它 们 有 偷 窃 的 坏 习 惯.",
		MONKEYBARREL = "",
		MONSTERLASAGNA = "我 做 出 来 什 么 了?",
		FLOWERSALAD = "好 新 鲜.",
        ICECREAM = "琪 露 诺?",
        WATERMELONICLE = "那 么 硬.",
        TRAILMIX = "替 代 食 品.",
        HOTCHILI = "有 点 辣 但 是 不 烫.",
        GUACAMOLE = "鳄 梨 在 哪 里?",
		MONSTERMEAT = "我 不 认 为 它 很 好 吃.",
		MONSTERMEAT_DRIED = "更 黑 了. 更 皱 了.",
		MOOSE = "这 个 是....",
		MOOSEEGG = "里 面 有 活 着 的 东 西.",
		MOSSLING = "它 们 胃 口 真 大.",
		FEATHERFAN = "最 有 效 的 风 扇!",
		TROPICALFAN = "最 有 效 的 风 扇!",
		GOOSE_FEATHER = "我 不 认 为 这 是 制 暖 用 的.",
		STAFF_TORNADO = "不 要 在 基 地 附 近 使 用.",
		MOSQUITO =
		{
			GENERIC = "按 蚊.",
			HELD = "我 要 杀 了 你.",
		},
		MOSQUITOSACK = "我 担 心 寄 生 虫.",
		MOUND =
		{
			DUG = "它 被 挖 开 了.",
			GENERIC = "坟 墓 下 面 有 特 别 的 东 西.",
		},
		NIGHTLIGHT = "它 让 我 的 思 维 冷 静 下 来.",
		NIGHTMAREFUEL = "让 人 的 噩 梦 可 视 化.",
		NIGHTSWORD = "我 很 容 易 就 能 控 制 它.",
		NITRE = "硝 酸 钾",
		ONEMANBAND = "额, 我 不 擅 长 表 演..",
		PANDORASCHEST = "典 型 的 地 下 城 奖 励，呵 呵?",
		PANFLUTE = "这 旋 律 让 人 昏 昏 欲 睡",
		PAPYRUS = "Sans 的 兄 弟.",
		PENGUIN = "它 们 有 后 代 吗?",
		PERD = "看 起 来 像 是 自 由 的 鸟.",
		PEROGIES = "这 个 名 字 象 征 着 着'节日'.",
		PETALS = "它 没 法 长 期 保 存.",
		PETALS_EVIL = "它 们 会 吸 收 心 智.",
		PICKAXE = "破 斧 头!",
		PIGGYBACK = "好 脏.",
		PIGHEAD = 
		{	
			GENERIC = "恶 心!",
			BURNT = "现 在，它 没 有 任 何 意 义 了.",
		},
		PIGHOUSE =
		{
			FULL = "我 能 感 觉 到 它 们 在 看 着 我.",
			GENERIC = "嗯，那 不 是 小 猪.",
			LIGHTSOUT = "我 知 道 是 你，猪!",
			BURNT = "它 烧 掉 了.",
		},
		PIGKING = "他 想 要 的 只 有 奢 侈 和 愉 悦.",
		PIGMAN =
		{
			DEAD = "好 恶 心.",
			FOLLOWER = "我 会 把 它 当 成 奴 隶.",
			GENERIC = "我 也 恨 你.",
			GUARD = "徒 劳 的 忠 诚.",
			WEREPIG = "停 止 你 的 入 侵!",
		},
		PIGSKIN = "杀 了 猪 人 的 战 利 品.",
		PIGTENT = "",
		PIGTORCH = "燃 烧 着 的 猪 人 图 腾.",
		PINECONE = 
		{
		    GENERIC = "我 只 是 单 纯 的 不 想 用 这 个.",
		    PLANTED = "当 它 们 长 大 后 你 就 区 分 不 出 来 了.",
		},
		PITCHFORK = "让 我 们 看 看 地 的 面 貌.",
		PLANTMEAT = "这 不 是 光 合 作 用 的 结 果.",
		PLANTMEAT_COOKED = "好 吧，它 至 少 闻 起 来 有 肉 的 味 道.",
		PLANT_NORMAL =
		{
			GENERIC = "种 点 什 么 东 西.",
			GROWING = "我 仍 然 无 法 理 解 农 民 的 思 想.",
			READY = "我 认 为 它 完 全 长 大 了.",
			WITHERED = "看 起 来 很 悲 伤...",
		},
		POMEGRANATE = "石 榴。它 对 女 性 的 皮 肤 很 好.",
		POMEGRANATE_COOKED = "好 吧，它 现 在 对 皮 肤 没 用 了.",
		POMEGRANATE_SEEDS = "石 榴 种 子",
		POND = "里 面 的 水 不 干 净.",
		POOP = "它 是 某 个 东 西..  真 的 是 某 个 东 西..",
		FERTILIZER = "依 旧 是...",
		PUMPKIN = "南 瓜 属",
		PUMPKINCOOKIE = "这 个 游 戏 里 最 好 的 零 食!!",
		PUMPKIN_COOKED = "它 更 软 了.",
		PUMPKIN_LANTERN = "万 圣 节!",
		PUMPKIN_SEEDS = "南 瓜 种 子.",
		PURPLEAMULET = "我 能 听 到 尖 叫 声.",
		PURPLEGEM = "象 征 着 精 神 的 死 亡.",
		RABBIT =
		{
			GENERIC = "它 一 定 比 帝 还 小.",
			HELD = "嗨! 小 家 伙.",
		},
		RABBITHOLE = 
		{
			GENERIC = "上 面 像 是 蚂 蚁 的 通 道.",
			SPRING = "它 们 讨 厌 下 雨.",
		},
		RAINOMETER = 
		{	
			GENERIC = "这 没 有 科 学 依 据.",
			BURNT = "更 没 用 了.",
		},
		RAINCOAT = "但 它 不 能 阻 止 我 鞋 子 被 弄 湿.",
		RAINHAT = "这 像 是 个 幼 儿 园 的 帽 子.",
		RATATOUILLE = "传 统 法 国 普 罗 旺 斯 炖 蔬 菜 盘.",
		RAZOR = "太 粗 糙 和 尖 锐.",
		REDGEM = "这 象 征 着 热 情.",
		RED_CAP = "典 型 伞 菌.但 这 不 是 关 键.",
		RED_CAP_COOKED = "吃 了 依 旧 会 对 身 体不 好.",
		RED_MUSHROOM =
		{
			GENERIC = "这 是 一 个 红 色 的 蘑 菇.",
			INGROUND = "它 们 只 在 白 天 出 现.",
			PICKED = "我 很 好 奇 他 还 会 长 出 来 吗?",
		},
		REEDS =
		{
			BURNING = "燃 烧.",
			GENERIC = "很 好 的 燃 料.",
			PICKED = "3 天 后 会 重 新 长 出 来.",
		},
        RELIC = 
        {
            GENERIC = "这 个 地 方 以 前 是 干 嘛 用 的?",
            BROKEN = "我 甚 至 猜 不 出 它 是 什 么.",
        },
        RUINS_RUBBLE = "这 可 以 被 修 复.",
        RUBBLE = "",
		RESEARCHLAB = 
		{	
			GENERIC = "我 已 经 知 道 了 它 的 一 切.",
			BURNT = "喔.. 它 很 悲 伤...",
		},
		RESEARCHLAB2 = 
		{
			GENERIC = "更 好 的 信 息  储 存 在 里 面.",
			BURNT = "它 烧 着 了.",
		},
		RESEARCHLAB3 = 
		{
			GENERIC = "这 个 一 个 阴 影 控 制 器.",
			BURNT = "现 在 它 比 阴 影 更 黑 了.",
		},
		RESEARCHLAB4 = 
		{
			GENERIC = "等 一 下, 这 个 魔 法 是 '那 个' 魔 法?",
			BURNT = "它 烧 着 了.",
		},
		RESURRECTIONSTATUE = 
		{
			GENERIC = "我 不 应 该 遵 循 食 谱 的..",
			BURNT = "它 现 在 没 用 了.",
		},
		RESURRECTIONSTONE = "我 将 会 在 这 里 复 活.",
		ROBIN =
		{
			GENERIC = "它 可 不 是 帝.",
			HELD = "不 要 害 怕, 小 家 伙.",
		},
		ROBIN_WINTER =
		{
			GENERIC = "它 可 不 是 帝.",
			HELD = "好 柔 软!",
		},
		ROBOT_PUPPET = "",
		ROCK_LIGHT =
		{ -- Not implemented
			GENERIC = "一 个 结 痂 的 熔 岩 坑.",
			OUT = "看 起 来 很 脆 弱.",
			LOW = "刚 刚 超 过 炕.",
			NORMAL = "好 舒 服.",
		},
		ROCK = "我 认 为 它 大 约 有 9.63 立 方 米.",
		ROCK_ICE = 
		{
			GENERIC = "跟 Chirno 一 样 冰 冷.",
			MELTED = "它 融 化 了.",
		},
		ROCK_ICE_MELTED = "它 融 化 了.",
		ICE = "Chirno 的 一 部 分.",
		ROCKS = "像 你 的 大 脑 一 样.",
        ROOK = "它 驾 驶 技 术 不 好.",
		ROPE = "依 旧 是多 叶 的",
		ROTTENEGG = "碳 酸 钙 的 成 分!",
		SANITYROCK =
		{
			ACTIVE = "它 是 一 个 激 活 的 岩 石.", -- big
			INACTIVE = "好 像 我 现 在 可 以 通 过 它 了.", -- small
		},
		SAPLING =
		{
			BURNING = "燃 烧",
			WITHERED = "它 因 热 而 枯 萎.",
			GENERIC = "这 是 一 棵 树 苗.",
			PICKED = "4 天 后 我 会 重 新 长 出 来.",
		},
		SEEDS = "我 不 知 道 里 面 有 什 么.",
		SEEDS_COOKED = "我 喜 欢 它 的 味 道.",
		SEWING_KIT = "游 戏 设 计 还 是 好 的.",
		SHOVEL = "工 人 的 象 征.",
		SILK = "我 如 何 用 它 来 制 作 呢??",
		SKELETON = "所 有 凡 人 的 最 终 归 宿.",
		SKELETON_PLAYER = "所 有 凡 人 的 最 终 归 宿.", -- It won't actually be spawned.
		SKULLCHEST = "呵 呵",
		SMALLBIRD =
		{
			GENERIC = "额.. 它 好 可 爱!",
			HUNGRY = "它 很 饿, 但 它 不 懂 如 何 表 达.",
			STARVING = "我 觉 得 它 会 饿 死 的.",
		},
		SMALLMEAT = "这 是 肉. 尽 管 很 小.",
		SMALLMEAT_DRIED = "好 僵 硬!",
		SPEAR = "原 始 的 矛.",
		SPIDER =
		{
			DEAD = "我 杀 了 它.",
			GENERIC = "它 可 不 是 山 女.",
			SLEEPING = "好 吧, 至 少 现 在 很 可 爱.",
		},
		SPIDERDEN = "额, 什 么 事 情 改 变 了..",
		SPIDEREGGSACK = "为 什 么 它...",
		SPIDERGLAND = "蜘 蛛 的 内 脏",
		SPIDERHAT = "令 人 毛 骨 悚 然 的 帽 子.",
		SPIDERQUEEN = "情 况 发 生 了 严 重 的 变 化!!",
		SPIDER_WARRIOR =
		{
			DEAD = "我 把 它 杀 了.",
			GENERIC = "它 的 攻 击 间 隔 比 较 长.",
			SLEEPING = "这 是 踢 开 它 的 好 机 会.",
		},
		SPOILED_FOOD = "腐 烂 堆 积",
		STATUEHARP = "从 游 戏 起 初 它 的 头 就 没 有 被 设 计.",
		STATUEMAXWELL = "破 玩 意.",
		STINGER = "它 无 毒.",
		STRAWHAT = "好 整 洁 漂 亮 的 帽 子.",
		STUFFEDEGGPLANT = "易 消 化 的 食 物.",
		SUNKBOAT = "调 试 项 目!",
		SWEATERVEST = "不 粘 人!",
		REFLECTIVEVEST = "闪 亮 的 背 心.",
		HAWAIIANSHIRT = "凉 爽!",
		TAFFY = "它 太 甜 啦!",
		TALLBIRD = "这 个... 是 变 形 的 生 物? 它 是 靠 什 么 活 下 来 的?",
		TALLBIRDEGG = "它 不 会 腐 烂.",
		TALLBIRDEGG_COOKED = "快看 '博尔克斯!'",
		TALLBIRDEGG_CRACKED =
		{
			COLD = "它 在 发 抖",
			GENERIC = "它 在 孵 化.",
			HOT = "太 热 了 它 受 不 了.",
			LONG = "我 不 应 该 帮 它 孵 化.",
			SHORT = "它 马 上 就 会 破 壳 而 出!",
		},
		TALLBIRDNEST =
		{
			GENERIC = "那 个 蛋 值 得 冒 险.",
			PICKED = "这 个 鸟 巢 是 空 的.",
		},
		TEENBIRD =
		{
			GENERIC = "如 果 它 完 全 长 大 了 会 怎 么 样?",
			HUNGRY = "他 饿 了.",
			STARVING = "我 觉 得 它 会 被 饿 死.",
		},
		TELEBASE =
		{
			VALID = "上 面 有 能 量 流 动.",
			GEMS = "它 需 要 更 多 的 紫 宝 石.",
		},
		GEMSOCKET = 
		{
			VALID = "这 里 设 置 传 输 坐 标.",
			GEMS = "需 要 一 个 紫 宝 石.",
		},
		TELEPORTATO_BASE =
		{
			ACTIVE = "它 准 备 把 我 带 离 这 个 世 界.",
			GENERIC = "这 链 接 到 另 一 维 度.",
			LOCKED = "仍 然 缺 了 点 东 西.",
			PARTIAL = "它 的 力 量 在 积 累.",
		},
		TELEPORTATO_BOX = "有 害 的 东 西 流 进 这 里 面.",
		TELEPORTATO_CRANK = "疯 狂 的 东 西 连 接 着 这 里.",
		TELEPORTATO_POTATO = "这 是 由 外 来 分 子 组 成 的.",
		TELEPORTATO_RING = "这 个 世 界 的 逻 辑 存 储 在 里 面.",
		TELESTAFF = "随 机 传 送.",
		TENT = 
		{
			GENERIC = "如 果 我 起 不 来 呢?",
			BURNT = "它 烧 掉 了.",
		},
		SIESTAHUT = 
		{
			GENERIC = "现 在 我 可 以 在 白 天 睡 觉 啦!",
			BURNT = "它 烧 掉 了",
		},
		TENTACLE = "小 心!",
		TENTACLESPIKE = "黏 黏 的 令 人 作 呕",
		TENTACLESPOTS = "可 以 用 来 防 水.",
		TENTACLE_PILLAR = "好 大 呀!",
		TENTACLE_PILLAR_ARM = "它 由 魔 法 力 量 产 生.",
		TENTACLE_GARDEN = "一 个 巨 兽 的 极 端.",
		TOPHAT = "我 能 叠 起 来 几 个 呢?",
		TORCH = "我 不 能 把 它 固 定 住 吗?",
		TRANSISTOR = "这 是 一 个 晶 体 管!",
		TRAP = "专 门 捕 获 傻 瓜!",
		TRAP_TEETH = "致 命 的 牙 齿",
		TRAP_TEETH_MAXWELL = "这 专 门 为 人 类 准 备!",
		TREASURECHEST = 
		{
			GENERIC = "用 来 装 东 西",
			BURNT = "它 烧 掉 了.",
		},
		TREASURECHEST_TRAP = "我 不 认 为 这 是 个 好 箱 子.",
		TREECLUMP = "它 阻 挡 我 了.",
		TRINKET_1 = "它 们 的 模 型 表 明 这 不 是 自 然 形 成 的.",
		TRINKET_10 = "异 常 的 干 净",
		TRINKET_11 = "因 为 心 中 的 内 疚 它 撒 谎 了.",
		TRINKET_12 = "那 么，这 东 西 有 什 么 用 呢?",
		TRINKET_2 = "这 是 一 个 人 工 制 品.",
		TRINKET_23 = "调 试 项 目",
		TRINKET_3 = "这 是 有 关 历 史 的 东 西 吗 还 是?",
		TRINKET_4 = "这 个 一 个.. 侏 儒!",
		TRINKET_5 = "儿 童 玩 具.",
		TRINKET_6 = "我 不 能 用 它 来 制 作.",
		TRINKET_7 = "儿 童 玩 具.",
		TRINKET_8 = "它 们 有 洗 过 澡 吗?",
		TRINKET_9 = "它 们 的 色 彩 好 漂 亮.",
		TRUNKVEST_SUMMER = "这 有 点 薄.",
		TRUNKVEST_WINTER = "很 棒 的 保 暖 衣 物",
		TRUNK_COOKED = "看 起 来 很 美 味",
		TRUNK_SUMMER = "这 皮 看 起 来 很 有 用.",
		TRUNK_WINTER = "多 余 的 脂 肪.",
		TUMBLEWEED = "我 很 好 奇 里 面 有 什 么 东 西.",
		TURF_CARPETFLOOR = "一 大 块 地 板.",
		TURF_CHECKERFLOOR = "一 大 块 地 板.",
		TURF_DIRT = "一 大 块 地 皮.",
		TURF_FOREST = "一 大 块 地 皮.",
		TURF_GRASS = "一 大 块 地 皮.",
		TURF_MARSH = "一 大 块 地 皮.",
		TURF_ROAD = "一 大 块 地 皮 .",
		TURF_ROCKY = "一 大 块 地 皮.",
		TURF_SAVANNA =" 一 大 块 地 皮.",
		TURF_WOODFLOOR = "一 大 块 地 皮.",
		TURKEYDINNER = "鸡 肉，就 是 这 样.",
		TWIGS = "我 不 能 做 弓 和 箭 吗?",
		UMBRELLA = "这 有 什 么 用?",
		GRASS_UMBRELLA = "这 个 真 的 有 什 么 用?",
		PALMLEAF_UMBRELLA = "这 有 什 么 用?",
		UNIMPLEMENTED = "",
		WAFFLES = "我 真 的 要 把 它 拿 在 手 上 吗?",
		WALL_HAY = 
		{	
			GENERIC = "我 可 不 能 让 火 碰 到 它.",
			BURNT = "烧 着 了.",
		},
		WALL_HAY_ITEM = "他 真 的 不 是 一 种 草 料 吗.",
		WALL_STONE = "比 其 他 的 好 多 了.",
		WALL_STONE_ITEM = "用 来 建 造 自 己 的 领 地.",
		WALL_RUINS = "看 起 来 像 黄 金 做 的.",
		WALL_RUINS_ITEM = "它 很 硬.",
		WALL_WOOD = 
		{
			GENERIC = "远 离 火 焰.",
			BURNT = "它 烧 着 了.",
		},
		WALL_WOOD_ITEM = "我 不 喜 欢 这 个.",
		WALRUS = "盖 尔 海 象 的 品 种",
		WALRUSHAT = "猎 人 帽 (+2)",
		WALRUS_CAMP =
		{
			EMPTY = "这 里 有 某 个 建 筑.",
			GENERIC = "我 觉 得.. 这 墙 里 有 很 多 石 头.",
		},
		WALRUS_TUSK = "这 有 什 么 用?",
		WARG = "它 是 一 条 大 狗. 除 非 杀 了 它，不 然 会 让 我 们 越 来 越 疲 惫.",
		WASPHIVE = "蜜 蜂 聚 集 地",
		WATERMELON = "这 是.. 萃 香!",
		WATERMELON_COOKED = "这 是.. 萃 香!",
		WATERMELONHAT = "萃 香 帽 子!",
		WETGOOP = "这 个 食 物 的 卡 路 里 肯 定 是 0.",
		WINTERHAT = "一 个 漂 亮 的 冬 帽.",
		WINTEROMETER = 
		{
			GENERIC = "这 不 仅 仅 是 一 个 远 程 定 时 器.",
			BURNT = "它 烧 掉 了.",
		},
		WORMHOLE =
		{
			GENERIC = "坑 道 虫?",
			OPEN = "真 的，令 人 毛 骨 悚 然.",
		},
		WORMHOLE_LIMITED = "呀, 比 平 时 看 起 来 的 更 糟 糕.",
		ACCOMPLISHMENT_SHRINE = "它 没 法 永 远 保持.",        
		LIVINGTREE = "为 什 么？这 是 完 全 正 常 的!",
		ICESTAFF = "冷 冻 效 果 比 琪 露 诺 好 多 了.",
		
        FLOTSAM = "它 们 中 的 某 些 物 品 应 该 很 特 殊.",

        SUNKEN_BOAT = {
            GENERIC = "它 对 我 有 点 用 处.",
            ABANDONED = "也 许 我 应 该 抓 住 它?",
        },
        SUNKEN_BOAT_BURNT = "它 烧 掉 了.",
   		SUNKEN_BOAT_TRINKET_1 = "我 不 需 要 这 个 来 计 算 距 离.", --sextant
		SUNKEN_BOAT_TRINKET_2 = "儿 童 玩 具.", --toy boat
		SUNKEN_BOAT_TRINKET_3 = "这 个 真 的 有 用?", --candle
		SUNKEN_BOAT_TRINKET_4 = "世 界 连 接 器 的 组 成 部 分", --sea worther
		SUNKEN_BOAT_TRINKET_5 = "常 见 的 钓 鱼 垃 圾.", --boot

		HOUNDFIRE = "它 很 烫! 小 心!",

		--- CAPY DLC ------------------------------------------------------------------------------------------------
		ANTIVENOM = "这 可 能 是 一 个 毒 素 或 抗 蛇 毒 血 清.",
		VENOMGLAND = "以 毒 攻 毒.",
		BLOWDART_POISON = "另 一 种 射 击 武 器!",
		OBSIDIANMACHETE = "这 是 一 个 热 的 工 具.",
		SPEARGUN_POISON = "目 标 将 会 痛 苦 的 死 去.",
		OBSIDIANSPEARGUN = "它 看 起 来 更 像 '被 诅 咒 的 火'",
		LUGGAGECHEST = "可 以 在 海 上 漂 浮 的 箱 子",
		PIRATIHATITATOR =
		{
			GENERIC = "里 面 的 魔 法 成 分 已 经 很 少 了.",
			BURNT = "它 烧 掉 了",
		},
		COFFEEBEANS = "我 闻 不 到 什 么.",
		COFFEE = "哈 哈 哈.. 就 是 这 样.",
		COFFEEBEANS_COOKED = "现 在 我 能 闻 到 味 道 了!",
		COFFEEBUSH =
		{
			BARREN = "它 需 要 浇 灌.",
			WITHERED = "热 量 毁 掉 了 它.",
			GENERIC = "它 看 起 来 好 像 大 王 花.",
			PICKED = "4 天 后 它 会 再 生 的.",
		},
		COFFEEBOT = "它 生 产 咖 啡.",
		MUSSEL = "为 什 么 吃 生 的 会 降 低 心 智?",
		MUSSEL_FARM =
		{
			 GENERIC = "没 有 检 测 出 霍 乱 弧 菌",
			 STICKPLANTED = "这 得 花 一 点 时 间."
		},

		MUSSEL_STICK = "蚌 类 会 黏 在 上 面.",
		LOBSTER = "被 龙 虾 抢 了.",
		LOBSTERHOLE = "那 是 一 只 龙 虾.",
		SEATRAP = "用 来 抢 龙 虾.",
		SAND_CASTLE =
		{
			SAND = "它 是 如 此 幼 稚.",
			GENERIC = "它 是 如 此 幼 稚."
		},
		BOATREPAIRKIT = "它 是 怎 么 制 作 的??",

		BALLPHIN = "它 又 小 又 可 爱!",
		BOATCANNON = "我 想 在 海 上 发 动 战 争.",
		BOTTLELANTERN = "过 于 传 统.",
		BURIEDTREASURE = "它 是 拿 来 发 酵 的 吗?",
		BUSH_VINE =
		{
			BURNT = "它 烧 着 了",
			CHOPPED = "4 天 后 会 再 长 出 来 的.",
			GENERIC = "它 们 中 可 能 藏 着 蛇.",
		},
		CAPTAINHAT = "这 让 我 想 起 了 舰....",
		COCONADE =
		{
			BURNING = "不 要 考 验 我 的 防 御 能 力.",
			GENERIC = "它 需 要 被 点 燃 才 能 爆 炸.",
		},
		CORAL = "碳 酸 钙 生 物",
		CORALREEF = "丰 富 的 浮 游 生 物",
		CRABHOLE = "这 是 一 个 螃 蟹 洞.",
		CUTLASS = "致 命 的 刀",
		DUBLOON = "让 我 们 做 个 决 定 吧.",
		FABRIC = "天 然 木 质 纤 维.",
		FISHINHOLE = "大 量 的 浮 游 生 物 在 这 里.",
		GOLDENMACHETE = "这 是 一 把 金 色 的 砍 刀.",
		JELLYFISH = "钵 水 母 纲 动 物.",
		JELLYFISH_PLANTED = "我 该 如 何 解 释 这 个?",
		JELLYJERKY = "异 常 坚 韧.",

		LIMPETROCK =
		{
			GENERIC = "霍 乱 的 根 源.",
			PICKED = "它 会 在 三 天 后 再 生.",
		},
		LOGRAFT = "它 几 乎 不 能 浮 起 来.",
		MACHETE = "用 来 砍 蔓 藤",
		MESSAGEBOTTLEEMPTY = "放 点 东 西 进 去 竟 会 很 有 意 义.",
		MOSQUITO_POISON = "疾 病 传 播 的 好 例 子.",
		OBSIDIANCOCONADE = "爆 炸 后 的 碎 片 会 让 它 们 死 亡.",
		OBSIDIANFIREPIT = "高 效 的 火 堆.",
		OX = "呃, 真 恶 心",
		PIRATEHAT = "谁 要 成 为 一 个 海 贼 王?",
		RAFT = "比 木 头 的 好 多 了.",
		ROWBOAT = "它 需 要 手 划。我 最 讨 厌 这 个 了.",
		SAIL = "不 用 再 用 手 划 啦!",
		SANDBAG_ITEM = "防 洪",
		SANDBAG = "防 洪",
		SEASACK = "自 然 地 泡 沫",
		SEASHELL_BEACHED = "双 壳 类 生 物",
		SEAWEED = "这 个 做 的 汤 很 美 味.",

		SEAWEED_PLANTED = "那 是 一 些 海 藻.",
		SLOTMACHINE = "赌 博 是 种 病.",
		SNAKE_POISON = "它 有 毒 性.",
		SNAKESKIN = "很 坚 韧.",
		SNAKESKINHAT = "坚 韧 的 帽 子",
		SOLOFISH = "谁 放 这 狗 出 来 的?",
		SPEARGUN = "这 就 像 步 枪",
		SPOILED_FISH = "腐 烂 的 鱼",
		SWORDFISH = "看 那 锋 利 的 上 颌.",
		TRIDENT = "这 是 用 于 白 刃 战 的.",
		TRINKET_13 = "因 为 某 些 原 因，我 不 想 打 开 它.",
		TRINKET_14 = "不 要 让 它 打 破.",
		TRINKET_15 = "白 色 主 教.",
		TRINKET_16 = "黑 色 主 教.", -- #TODO: Why is this here?
		TRINKET_17 = "有 价 值 的 垃 圾",
		TRINKET_18 = "好 吧, 它 确 实 已 经 坏 了.",
		TRINKET_19 = "可 疑 的 药 丸", -- #TODO: What is this?
		TURBINE_BLADES = "难 以 置 信，它 竟 然 是 塑 料.",
		TURF_BEACH = "一 大 块 地 皮.",
		TURF_JUNGLE = "一 大 块 地 皮.",
		VOLCANO_ALTAR = --#T
		{
			GENERIC = "火 山 入 口",
			OPEN = "祭 坛 准 备 好 了.",
		},
		VOLCANO_ALTAR_BROKEN = "可 以 修 好",
		WHALE_BLUE = "我 知 道 鲸 鱼 的 脸 总 是 充 满 快 乐 的..",
		WHALE_CARCASS_BLUE = "我 可 以 用 砍 刀 砍.",
		WHALE_CARCASS_WHITE = "我 可 以 用 砍 刀 砍.",

		ARMOR_SNAKESKIN = "它 像 一 个 绅 士 的 帽 子.",
		CLOTHSAIL = "竹 帆.",
		DUG_COFFEEBUSH = "当 然，这 是 一 个 大 王 花..",
		LAVAPOOL = "这 充 满 刺 激 性 气 体.",
		BAMBOO = "它 空 荡 的 身 躯 意 味 着 正 直.",
		AERODYNAMICHAT = "地 上 住 的 人 会 把 我 看 成 是 鲨 鱼.",
		POISONHOLE = "闻 起 来 很 糟!",
		BOAT_LANTERN = "航 行 的 重 要 物 品.",
		DEAD_SWORDFISH = "它 的 喙 看 起 来 很 有 用.",
		LIMPETS = "推 荐 烹 饪 之 后 再 食 用.",
		JELLYFISH_COOKED = "橙 色 的 洋 葱 圈.",
		OBSIDIANAXE = "这 是 一 个 会 发 热 工 具.",
		COCONUT = "我 光 用 双 手 对 它 毫 无 办 法.",
		COCONUT_COOKED = "它 恢 复 9.375 的 饥 饿.",
		BERMUDATRIANGLE = "这 就 像 百 慕 大 群 岛 三 角 洲.",
		SNAKE = "砍 它 的 脖 子!",
		SNAKEOIL = "这 是 干 什 么 用 的?'",
		ARMORSEASHELL = "双 层 盔 甲",
		SNAKE_FIRE = "这 是 阴 蛇 火?",
		MUSSEL_COOKED = "这 应 该 放 进 面 条 里.",

		PACKIM_FISHBONE = "这 不 是.. 一 根 正 常 的 腐 烂 鱼 骨.",
		PACKIM = "可 以 飞 的 储 存 箱!",

		ARMORLIMESTONE = "多 么 丑 陋 的 盔 甲",
		TIGERSHARK = "它 们 是 怎 么 制 造 了 这 个 糟 糕 的 多 核 体 生 物?",
		WOODLEGS_KEY1 = "这 是 释 放 某 个 人 的 钥 匙 之 一.",
		WOODLEGS_KEY2 = "这 是 释 放 某 个 人 的 钥 匙 之 一.",
		WOODLEGS_KEY3 = "这 是 释 放 某 个 人 的 钥 匙 之 一.",
		WOODLEGS_CAGE = "这 就 是 我 必 须 要 去 救 的 ‘那 个 人’.",
		OBSIDIAN_WORKBENCH = "看 起 来 像 个 热 板 凳.",

		NEEDLESPEAR = "并 不 重 但 是 很 锋 利.",
		LIMESTONE = "很 多 艺 术 的 杰 作 都 由 它 组 成.",
		DRAGOON = "你 不 是 一 只 四 条 腿 的, 恩?",

		ICEMAKER = {
			OUT = "它 需 要 更 多 的 燃 料.",
			VERYLOW = "它 运 行 得 很 慢.",
			LOW = "它 的 速 率 正 在 下 降.",
			NORMAL = "目 前 为 止 它 运 行 良 好.",
			HIGH = "它 运 行 的 棒 极 了.",
		},

		DUG_BAMBOOTREE = "我 应 该 种 这 个.",
		BAMBOOTREE =
		{
			BURNT = "它 烧 着 了",
			CHOPPED = "我 想 它 4 天 后 会 再 长 出 来.",
			GENERIC = "里 面 是 空 的.",
		},
		JUNGLETREE =
		{
			BURNING = "燃 烧",
			BURNT = "它 烧 着 了",
			CHOPPED = "我 觉 得 我 很 缺 这 个?",
			GENERIC = "热 带 树 木 都 跟 它 一 样 的 高.",
		},
		SHARK_GILLS = "这 不 是 一 块 老 虎 皮?",
		OBSIDIAN = "嗯，这 黑 色 的.",
		BABYOX = "这 是 一 个 很 小 的 肉 食 动 物.",
		STUNGRAY = "当 心 有 毒!",
		SHARK_FIN = "我 靠，我 刚 刚 剪 了 它 的 整 个 鳍!",
		FROG_POISON = "小 心!",
		ARMOUREDBOAT = "这 是 一 条 与 浪 作 斗 争 的 船.",
		ARMOROBSIDIAN = "我 觉 得 它 比 木 头 软 多 了.",
		BIOLUMINESCENCE = "不 切 实 际. 但 很 漂 亮.",
		SPEAR_POISON = "多 么 有 效 的 武 器.",
		SPEAR_OBSIDIAN = "这 是 个 会 发 热 的 武 器.",
		SNAKEDEN =
		{
			BURNT = "它 烧 掉 了.",
			CHOPPED = "它 被 切 碎 了.",
			GENERIC = "里 面 有 蛇.",
		},
		TOUCAN = "它 实 际 上 是 食 肉 鸟.",
		MESSAGEBOTTLE = "真 的 藏 宝 图!",
		SAND = "硅, 二 氧 化 硅, 氯 化 钠...构 成 的 混 合 物",
		SANDHILL = "这 是 一 座 山. 虽 然 很 小.",
		PEACOCK = "它 包 括 了 P. muticus P. cristatus.",
		VINE = "耐 用 的 枝 条.",
		SUPERTELESCOPE = "尽 管 滤 镜 没 有 最 优 化",
		SEAGULL = "看 起 来 很 胖！不 许 拉 便 便!",
		SEAGULL_WATER = "看 起 来 很 胖！不 许 拉 便 便!",
		PARROT = "它 在 嘲 笑 我",
		ARMOR_LIFEJACKET = "就 算 是 我 也 需 要 这 个 因 为 我 不 可 能 一 直 游 泳.",
		WHALE_BUBBLES = "水 下 有 巨 兽.",
		EARRING = "好 的 配 饰!",
		ARMOR_WINDBREAKER = "我 很 喜 欢 它 的 颜 色.",
		SEAWEED_COOKED = "跟 盆 摘 没 什 么 区 别.",
		CARGOBOAT = "它 有 一 个 奇 怪 的 红 色 部 分.",
		GASHAT = "最 奇 怪 的 事 情",
		ELEPHANTCACTUS = "具 有 攻 击 性 的 植 物!",
		DUG_ELEPHANTCACTUS = "你. 已 被 控 制.",
		ELEPHANTCACTUS_ACTIVE = "小 心 尖 刺!",
		ELEPHANTCACTUS_STUMP = "它 们 再 给 尖 刺 充 能.",
		FEATHERSAIL = "带 羽 毛 的 帆!",
		WALL_LIMESTONE_ITEM = "好 伤 心，我 不 能 做 出 这 样 的 杰 作.",
		JUNGLETREESEED = "",
		VOLCANO = "我 可 以 爬 上 那 里.",
		IRONWIND = "工 业 革 命!",
		SEAWEED_DRIED = "我 要 海 带 汤!",
		TELESCOPE = "超 视 觉",
		
		DOYDOY = "你 到 底 应 该 是 什 么 样 的?",
		DOYDOYBABY = "可 爱，至 少..",
		DOYDOYEGG = "蠢 蛋.",
		
		DOYDOYEGG_CRACKED = "孵 化",
		DOYDOYFEATHER = "又 轻 又 软..",
		DOYDOYNEST = "也 许 我 该 离 开 一 会.",

		PALMTREE =
		{
			BURNING = "燃 烧",
			BURNT = "它 烧 掉 了.",
			CHOPPED = "它 被 砍 了.",
			GENERIC = "小 心 掉 落 的 东 西",
		},
		PALMLEAF = "多 大 的 叶 子，可 能 是 有 用 的.",
		CHIMINEA = "防 风 坑",
		DOUBLE_UMBRELLAHAT = "这 用 来 做 什 么?",
		CRAB = {
			GENERIC = "我 靠，螃 蟹!",
			HIDDEN = "哈, 螃 蟹!",
		},
		TRAWLNET = "捕 鱼!",
		TRAWLNETDROPPED = {
			SOON = "肯 定 在 下 沉.",
			SOONISH = "我 觉 得 在 下 沉.",
			GENERIC = "它 下 沉.",
		},
		VOLCANO_EXIT = "这 是 一 个 出 口.",
		SHARX = "让 我 想 起 了 大 白 鲨.",
		SEASHELL = "村 纱 喜 欢 这 个.",
		WHALE_BUBBLES = "水 下 有 巨 大 的 野 兽.",
		MAGMAROCK = "挖!",
		MAGMAROCK_GOLD = "这 里 有 黄 金.",
		CORAL_BRAIN_ROCK = "你 是 一 颗 有 智 慧 的 树 吗?",
		CORAL_BRAIN = "我 靠, 太 恐 怖 了!",
		SHARKITTEN = "它 们 是 怎 做 出 来 这 么 恐 怖 的 多 核 体 生 物 的?",
		SHARKITTENSPAWNER = 
		{
			GENERIC = "我 能 听 到 猫 叫 般 的 声 音.",
			INACTIVE = "这 是 很 特 别 的 东 西.",
		},
		LIVINGJUNGLETREE = "这 是 完 全 正 常 的",
		WALLYINTRO_DEBRIS = "遇 难 船 的 一 部 分.",
		MERMFISHER = "好 恐 怖",
        
        PRIMEAPE = "你 最 好 不 要 做 可 疑 的 事 情.",
        PRIMEAPEBARREL = "(叹 气)",

        REDBARREL = "你 明 显 想 打 破 这 个.",
        PORTAL_SHIPWRECKED = "它 完 全 坏 了.",

		MARSH_PLANT_TROPICAL = "拜 托, 我 不 想 得 到 命 令 离 开 这 里!! - 来 自 MOD 制 作 人 员",

		TELEPORTATO_SW_POTATO = "这 是 某 种 东 西 的 成 分.",
		PIKE_SKULL = "哎 哟.",
		PALMLEAF_HUT = "课 间 休 息 的 好 地 方.",
		FISH_RAW_SMALL_COOKED = "现 在 可 以 吃 了.",
		LOBSTER_DEAD = "嗯，好 吃.",
		MERMHOUSE_FISHER = "....",
		WILDBOREGUARD = "它 有 攻 击 性.",
		PIRATEPACK = "穿 上 就 能 赚 钱.",
		TUNACAN = "谁 能?",
		MOSQUITOSACK_YELLOW = "好 脏",
		SANDBAGSMALL = "防 止 洪 水!",
		FLUP = "给 我 滚 开!",
		OCTOPUSKING = "我 能 摸 一 下 你 的 皮 吗?",
		OCTOPUSCHEST = "未 知 的 奖 励.",
		GRASS_WATER = "被 水 淹 了 的 草.",
		WILDBOREHOUSE = "这 是 一 个.. 房 子!",
		FISH_RAW_SMALL = "在 它 腐 烂 之 前 吃 掉",
		TURF_SWAMP = "一 大 块 地 皮.",
		FLAMEGEYSER = "保 持 距 离",
		KNIGHTBOAT = "你 最 好 离 我 远 点.",
		MANGROVETREE_BURNT = "我 很 好 奇 这 是 怎 么 发 生 的.",
		TIDAL_PLANT = "这 是 一 个 潮 汐 植 物",
		WALL_LIMESTONE = "这 是 一 堵 墙",
		FISH_RAW = "一 大 块 鱼 肉.",
		LOBSTER_DEAD_COOKED = "让 我 们 吃 掉 它 吧",
		JELLYFISH_DEAD = "x_x",
		BLUBBERSUIT = "这 就 像 内 脏. 讨 厌",
		BLOWDART_FLUP = "眼 睛 看 到 的.",
		TURF_MEADOW = "一 大 块 地 皮.",
		TURF_VOLCANO = "一 大 块 地 皮.",
		SWEET_POTATO = "红 薯?",
		SWEET_POTATO_COOKED = "烤 红 薯.",
		SWEET_POTATO_PLANTED = "这 是 红 薯!",
		SWEET_POTATO_SEEDS = "红 薯 种 子.",
		BLUBBER = "悲 叹..",
		TELEPORTATO_SW_RING = "它 就 像 一 个 腐 烂 的 海 藻",
		TELEPORTATO_SW_BOX = "像 个 某 个 东 西 的 一 部 分.",
		TELEPORTATO_SW_CRANK = "像 一 个 扫 帚",
		TELEPORTATO_SW_BASE = "我 想 这 正 是 缺 少 的 部 分.",
		VOLCANOSTAFF = "[技 能] 陨 石 撞 击",
		THATCHPACK = "绿 色 的 东 西",
		TURF_DESERTDIRT = "一 大 块 地 皮.",
		SHARK_TEETHHAT = "看 起 来 有 点 危 险",
		TURF_ASH = "一 大 块 地 皮.",
		TURF_FUNGUS_GREEN = "一 大 块 地 皮.",
		BOAT_TORCH = "这 可 以 让 我 呆 在 海 洋 中.",
		MANGROVETREE = "咸 的!",
		HAIL_ICE = "Chirn-y.",
		TROPICAL_FISH = "典 型 的 热 带 鱼.",
		TIDALPOOL = "我 可 以 钓 鱼.",
		WHALE_WHITE = "你 看 起 来 疯 了",
		VOLCANO_SHRUB = "喂? 你 还 活 着 吗?",
		ROCK_OBSIDIAN = "那 是..一 个 黑 曜 石!",
		ROCK_CHARCOAL = "我 认 为 这 是 一 个 黑 曜 石!",
		DRAGOONDEN = "这 不 是 一 个 '传 送 门'.",
		WILBUR_UNLOCK = "它 像 个 帝 王.",
		WILBUR_CROWN = "这 是 只 大 小 很 怪 异 的 猴 子.",
 
		TWISTER = "活 着 的 龙 卷 风!",
		TWISTER_SEAL = "嘿! 你.. 要..",
		MAGIC_SEAL = "我 可 以 感 觉 到 这 里 有 大 量 的 魔 法 能 量.",
		SAIL_STICK = "制 造 大 风!",
		WIND_CONCH = "制 造 龙 卷 风!",
		DRAGOONEGG = "这 是 一 颗 龙 蛋.",
		BUOY = "有 用 的 标 记.", 
		TURF_SNAKESKINFLOOR = "一 大 块 地 皮.",
        DOYDOYNEST = "这 是 一 个 笨 鸟 巢",

		ARMORCACTUS ="这 是 荆 棘 之 甲.",
		BIGFISHINGROD = "这 么 大 的 东 西 怎 么 能 放 进 我 的 库 存.",
		BOOK_METEOR = "哦，我 可 以 做 这 个!",
		BRAINJELLYHAT = "我 不 想 用 这 个 的 情 况 下 获 得 知 识.",
		COCONUT_HALVED = "它 可 以 回 复 4.6875 的 饥 饿 值.",
		CRATE = "看 看 里 面 有 什 么.",
		DEPLETED_BAMBOOTREE = "它 会 再 生 的.",
		DEPLETED_BUSH_VINE = "它 会 再 生 的.",
		DEPLETED_GRASS_WATER = "它 会 再 生 的.",
		DOYDOYEGG_COOKED = "看 着 有 点 '糊'",
		DRAGOONHEART = "龙 的 心 脏... 等 一 会,",
		DRAGOONSPIT = "火 焰 唾 液",
		DUG_BUSH_VINE = "我 应 该 种 这 个",
		FRESHFRUITCREPES = "喔, 我 应 该 做 这 个!",
		KRAKEN = "喔,,.. 你 好 呀?",
		KRAKENCHEST = "典 型 的 BOSS 奖 励!",
		KRAKEN_TENTACLE = "小 心!",
		MAGMAROCK_FULL = "挖 它!",
		MAGMAROCK_GOLD_FULL = "里 面 有 黄 金.",
		MONKEYBALL = "仿 制 球",
		MONSTERTARTARE = "我 不 想 吃 这 个..",
		MUSSELBOUILLABAISE = "这 是 马 赛 鱼 汤",
		MYSTERYMEAT = "完 全 浪 费",
		OXHAT = "看 起 来 有 点 紧!",
		OX_FLUTE = "下 雨 的 旋 律..?",
		OX_HORN = "这 是 牛 角.",
		PARROT_PIRATE = "你 最 好 说 点 什 么!",
		PEG_LEG = "我 可 以 用 它 来 攻 击 吗?",
		PIRATEGHOST = "哦，你 也 是 不 死 族.",
		SANDBAGSMALL_ITEM = "防 止 洪 水!",
		SHADOWSKITTISH_WATER = "你 最 好 离 我 远 点.",
		SHIPWRECKED_ENTRANCE = "",
		SHIPWRECKED_EXIT = "",
		SNAKESKINSAIL = "艰 难 的 航 行",
		SPEAR_LAUNCHER = "我 不 敢 相 信 这 是 一 把 枪.",
		SWEETPOTATOSOUFFLE = "Kyouko 蛋 奶 酥",
		SWIMMINGHORROR = "你 最 好 离 我 远 点.",
		TIGEREYE = "我 讨 厌 眼 珠 子.",
		TRINKET_20 = "为 什 么 是 个 抓 扒 工 具.",
		TRINKET_21 = "破 损 的 厨 具.",
		TRINKET_22 = "这 个 有 价 值 吗?",
		TURF_FUNGUS_RED = "一 大 块 地 皮.",
		TURF_MAGMAFIELD = "一 大 块 地 皮.",
		TURF_TIDALMARSH = "一 大 块 地 皮.", --汉化BY周洁楠
		VOLCANO_ALTAR_TOWER = "宏 伟 的 结 构.",
		WATERYGRAVE = "试 试 这 个!",
		WHALE_TRACK = "这 是 鲸 鱼 的 痕 迹!",
		WILDBOREHEAD = "不 好 闻.",
		WOODLEGSBOAT = "无 赖 汉 的 聚 合 处.",
		WOODLEGSHAT = "它 让 我 看 起 来 像 坏 血 病 ...我 的 意 思 是 好 可 怕!?",
		WOODLEGSSAIL = "经 典 的 海 盗 船.",
		WRECK = "我 不 能 修 复 它",
		INVENTORYGRAVE = "",
        INVENTORYMOUND = "",
		LIMPETS_COOKED = "很 好 闻 呢",
		RAWLING = "有 点 怪 异.",
		
		ENCRUSTEDBOAT = "Can this be floated?",
        BABYOX = "That's not cute.",
        BALLPHINHOUSE = "Ballphin's house. More like playgounds",
        DORSALFIN = "The dorsal fin of.. carbone?",
        NUBBIN = "A coral starter",
        CORALLARVE = "The seed of coral.",
        RAINBOWJELLYFISH = "This one might use most of the energy for lit.",
        RAINBOWJELLYFISH_PLANTED = "A colorful blob of science.",
        RAINBOWJELLYFISH_DEAD = "Was this a Self-luminous?",
        RAINBOWJELLYFISH_COOKED = "The color never dim.",
        RAINBOWJELLYJERKY = "What a painted jerky",
        WALL_ENFORCEDLIMESTONE = "I hope this doesn't rot.",
        WALL_ENFORCEDLIMESTONE_ITEM = "Won't this rot?",
        CROCODOG = "Shipwreked version of hounds. Still aggressive.",
        POISONCROCODOG = "A radioactive mutation.",
        WATERCROCODOG = "OK, this looks more radioactive..",
        QUACKENBEAK = "This one is like an obsidian with more hardness.",
        QUACKERINGRAM = "Almost invincible!",
		
		CAVIAR = "Developers couldn't put this game an salmon-roe-sushi.",
        CORMORANT = "Phalacrocorax spp. This one used to catch some fishes.",

        FISH3 = "Your color looks purple but not Yukari.",
        FISH4 = "Some tropical fishes may colored like this I think.",
        FISH5 = "A Solid-colored Paracheirodon.",

        FISH3_COOKED = "Now you don't even look like Yukari.",
        FISH4_COOKED = "It looks like Ananas flavor.",
        FISH5_COOKED = "Oh, It's not solid-colored inside.",

        FISH_FARM = 
        {
            EMPTY = "I must find roe if I'm to raise captive fish.",
            STOCKED = "I believe this should work.",
            ONEFISH = "It works at least.",
            TWOFISH = "It seems to be doing quite well.",
            REDFISH = "Not quite bad.",
            BLUEFISH  = "I need to harvest this right now.",
        },

        ROE = "With some rice would be perfect.",
        ROE_COOKED = "All I needed to do was just put this on rice.",
        
        SEA_YARD = 
        {
            ON = "What an over-technology.",
            OFF = "It needs tar to work again.",
            LOWFUEL = "It needs energy source.",
        },
        SEA_CHIMINEA =
        {
            EMBERS = "It is going to be disappeared.",
			GENERIC = "Boring.",
			HIGH = "Much warmer.",
			LOW = "Better put some fuels on it.",
			NORMAL = "What's the next plan?",
			OUT = "Well, that's over.",
        }, 

        TAR = "It looks like coal tar rather than asphalt.",
        TAR_EXTRACTOR =
        {
            ON = "It's working now",
            OFF = "I must switch it on to begin tar extraction.",
            LOWFUEL = "I'll need to refuel it if I want more tar.",
        },
        TAR_POOL = "This is real natural tar seep.",

        TARLAMP = "Smells bad.",
        TARSUIT = "Argh, should I pour this on?",
        TAR_TRAP = "Dirtiest trap ever.",

        TROPICALBOUILLABAISSE = "Traditional Provençal fish stew.",

        RESEARCHLAB5 = "I don't even know what I've made...",
        WATERCHEST = "Hope this doesn't flew away.",
        QUACKENDRILL = "I can get more tar if I used this at sea.",
        HARPOON = "One of the most primitive fishing mechanism.",
        MUSSEL_BED = "I should be careful setting it.",
		
		
		-------------- Examinations of shadow creatures ---------------
		CREAWLINGNIGHTMARE = "Reincarnation. Your existence is unlimited.",
		NIGHTMAREBEAK = "Reincarnation. Your existence is unlimited.",
		CRAWLINGHORROR = "Improbitas. Licks human of greed.",
		TERRORBEAK = "Damnatio. Your execution style is brutal.",
		SWIMMINGHORROR = "Sailing the Virgin Oceans. You know the way, huh?",
		SHADOWWATCHER = "Espinaje. What are you spying?",
		SHADOWSKITTISH = "Unexpected. You, are not intended.",
		SHADOWSKITTISH_WATER = "Viscidus. You are the scrap.",
		CREEPYEYES = "Superintentor. But you can't see inside.",
	},
	DESCRIBE_GENERIC = "我 甚 至 对 它 一 无 所 知.",
	DESCRIBE_TOODARK = "太 黑 了!",
	DESCRIBE_SMOLDERING = "那 东 西 就 要 着 火 了.",
	
	DESCRIBE_LOWPOWER = "我 没 有 足 够 的 妖 力!",
	DESCRIBE_NOSKILL = "我 还 没 学 会 技 能.",
	DESCRIBE_INVINCIBILITY_DURATION = "隐 形 的 时 间 增 加.",
	DESCRIBE_CLOAKING = "它 们 不 知 道 我 在 哪 里.",
	DESCRIBE_DECLOAKING = "我 已 经 不 再 隐 形 了!",
	DESCRIBE_CANNOTRESIST = "如 果 这 样 做，我 将 无 法 承 受 更 多.",
	DESCRIBE_NOREINFORCE = "我 不 再 被 加 强!",
	DESCRIBE_EYEHURT = "哦! 我 的 眼 睛!",
	DESCRIBE_NEWSIGHT = "让 我 们 看 看 这 个.",
	DESCRIBE_DONEEFFCT = "完 成 了.",
	DESCRIBE_NOSPAWN = "我 不 能 生 成.",
	DESCRIBE_TOOMANYBUTTER = "我 觉 得 这 足 够 了..?",
	DESCRIBE_ABILITY_ALREADY = "我 已 经 有 这 个 能 力 了.",
	DESCRIBE_HATUPGRADE = "帽 子 升 级",
	DESCRIBE_NOHANDED = "我 手 里 必 须 拿 点 东 西.",
	DESCRIBE_DONEUPGRADE = "\n升 级 完 成",
	DESCRIBE_INVINCIBILITY_ACTIVE = "触 发 无 敌",
	DESCRIBE_INVINCIBILITY_DONE = "我 不 再 是 无 敌 的.",
	DESCRIBE_UPGRADE_FREE = "\n现 在 可 以 免 费 升 级",
	DESCRIBE_UPGRADE_HEALTH = "我 不 能 变 得 更 强 了.",
	DESCRIBE_UPGRADE_HUNGER = "我 处 于 最 大 卡 路 里 燃 烧 状 态.",
	DESCRIBE_UPGRADE_SANITY = "恩.. 什 么 都 没 改 变.",
	DESCRIBE_UPGRADE_POWER = "我 已 经 拥 有 了 相 同 的 力 量.",
}