local require = GLOBAL.require
local STRINGS = GLOBAL.STRINGS
local ACTIONS = GLOBAL.ACTIONS
local Language = GLOBAL.YUKARI_LANGUAGE
local TUNING = GLOBAL.TUNING.YUKARI

STRINGS.CHARACTER_TITLES.yakumoyukari = "Youkai of Boundaries"
STRINGS.CHARACTER_NAMES.yakumoyukari = "Yakumo Yukari"
STRINGS.CHARACTER_DESCRIPTIONS.yakumoyukari = "has own ability 'youkai power'.\nbecomes dreadful when she obtains the power from the world."
STRINGS.CHARACTER_QUOTES.yakumoyukari = "\"I have taken the first napkin.\""
STRINGS.CHARACTERS.YAKUMOYUKARI = require "speech_yakumoyukari"

STRINGS.NAMES.YUKARIUMBRE = "Yukari parasol"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.YUKARIUMBRE = "I can spawn Scheme with this."
STRINGS.NAMES.YUKARIHAT = "Yukari Hat"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.YUKARIHAT = "This will gain my power."
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.TUNNEL = "I linked to other space."
STRINGS.NAMES.SCHEME = "Scheme"
STRINGS.TABS.TOUHOU = "TOUHOU"

STRINGS.NAMES.HEALTHPANEL = "Health Upgrade"
STRINGS.RECIPE_DESC.HEALTHPANEL = "Upgrade Health"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHPANEL = "A big health panel?"
STRINGS.NAMES.HUNGERPANEL = "Hunger Upgrade"
STRINGS.RECIPE_DESC.HUNGERPANEL = "Upgrade Hunger"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERPANEL = "This may make me less hungry."
STRINGS.NAMES.SANITYPANEL = "Sanity Upgrade"
STRINGS.RECIPE_DESC.SANITYPANEL = "Upgrade Sanity"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYPANEL = "Um.. a brain's in it."
STRINGS.NAMES.POWERPANEL = "Power Upgrade"
STRINGS.RECIPE_DESC.POWERPANEL = "Upgrade Power"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERPANEL = "Is this my power look like?!"
STRINGS.NAMES.HEALTHULT = "Jade Yin and Yang"
STRINGS.RECIPE_DESC.HEALTHULT = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHULT = "My partner's power"
STRINGS.NAMES.HUNGERULT = "Bagua"
STRINGS.RECIPE_DESC.HUNGERULT = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERULT = "I feel whole world's power is in it."
STRINGS.NAMES.SANITYULT = "The Third Eye"
STRINGS.RECIPE_DESC.SANITYULT = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYULT = "The eyes read people's minds."
STRINGS.NAMES.POWERULT = "The Boundary"
STRINGS.RECIPE_DESC.POWERULT = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERULT = "It is who I am."
STRINGS.NAMES.HEALTHULTSW = "The Gungnir"
STRINGS.RECIPE_DESC.HEALTHULTSW = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHULTSW = "I can feel the vampire's cruel."
STRINGS.NAMES.HUNGERULTSW = "Laevateinn"
STRINGS.RECIPE_DESC.HUNGERULTSW = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERULTSW = "This emblem means 'destroy'."
STRINGS.NAMES.SANITYULTSW = "Cherry Blossom"
STRINGS.RECIPE_DESC.SANITYULTSW = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYULTSW = "My friend circle."
STRINGS.NAMES.POWERULTSW = "The Emblem"
STRINGS.RECIPE_DESC.POWERULTSW = "Unlocks ultimate ability"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERULTSW = "It is who I am."

STRINGS.NAMES.SPELLCARD_TEST = "The Test"
STRINGS.RECIPE_DESC.SPELLCARD_TEST = "YOU CAN'T SEE THIS EVER."
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_TEST = "Boundary of Developers and Normal Players. :D"
STRINGS.NAMES.SPELLCARD_MESH = "Mesh of Light and Darkness"
STRINGS.RECIPE_DESC.SPELLCARD_MESH = "Inverts Sanity"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_MESH = "Inverts my sanity. \nPower Cost : "..TUNING.SPELLMESH_POWERCOST
STRINGS.NAMES.SPELLCARD_AWAY = "Yakumo Yukari's Spiriting Away"
STRINGS.RECIPE_DESC.SPELLCARD_AWAY = "Becomes invisible"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_AWAY = "Makes me invisible. \nPower Cost/sec : "..TUNING.SPELL_POWERCOST_NORMAL
STRINGS.NAMES.SPELLCARD_NECRO = "Necro Fantasia"
STRINGS.RECIPE_DESC.SPELLCARD_NECRO = "Makes Land of Death"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_NECRO = "Let everything into death. \nPower Cost : "..TUNING.SPELLNECRO_POWERCOST
STRINGS.NAMES.SPELLCARD_CURSE = "Curse of Dreams and Reality"
STRINGS.RECIPE_DESC.SPELLCARD_CURSE = "Converts Insanity to violence"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_CURSE = "Converts insanity to dreadfulness. \nPower Cost/sec : "..(TUNING.SPELL_POWERCOST_NORMAL * 3)
STRINGS.NAMES.SPELLCARD_BALANCE = "Balance of Motion and Stillness"
STRINGS.RECIPE_DESC.SPELLCARD_BALANCE = "Make items in inventory fresh"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BALANCE = "Set item in inventory fresh state. \nPower Cost : "..TUNING.SPELLBALANCE_POWERCOST.."\nSanity Cost : "..TUNING.SPELLBALANCE_SANITYCOST
STRINGS.NAMES.SPELLCARD_LAPLACE = "Magic Eye \"Laplace's Demon\""
STRINGS.RECIPE_DESC.SPELLCARD_LAPLACE = "Watch with her eyes"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_LAPLACE = "Watch world with my eyes. \nPower Cost/sec : "..(TUNING.SPELL_POWERCOST_NORMAL / 2).."\nSanity Cost : "..TUNING.SPELLLAPLACE_SANITYCOST
STRINGS.NAMES.SPELLCARD_BUTTER = "Bewitching Butterfly"
STRINGS.RECIPE_DESC.SPELLCARD_BUTTER = "Spawns butterflies"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BUTTER = "Spawns butterflies. \nPower Cost : "..TUNING.SPELLBUTTER_POWERCOST
STRINGS.NAMES.SPELLCARD_BAIT = "Bewitching Bait"
STRINGS.RECIPE_DESC.SPELLCARD_BAIT = "Create protective barrier."
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BAIT = "Creates a protective barrier while attracting nearby creatures. \nPower Cost/sec : "..TUNING.SPELL_POWERCOST_NORMAL
STRINGS.NAMES.SPELLCARD_ADDICTIVE = "Addictive Bait"
STRINGS.RECIPE_DESC.SPELLCARD_ADDICTIVE = "Rejuvenate nearby plants"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_ADDICTIVE = "Rejuvenate nearby plants. \nPower Cost : "..TUNING.SPELLADDICTIVE_POWERCOST.."\nSanity Cost : "..TUNING.SPELLADDICTIVE_SANITYCOST
STRINGS.NAMES.SPELLCARD_LAMENT = "Urashima's Box"
STRINGS.RECIPE_DESC.SPELLCARD_LAMENT = "Spawns random items"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_LAMENT = "Spawns random items. \nPower Cost : "..TUNING.SPELLLAMENT_POWERCOST
STRINGS.NAMES.SPELLCARD_MATTER = "Universe of Matter and Antimatter"
STRINGS.RECIPE_DESC.SPELLCARD_MATTER = "Repairs all physical items"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_MATTER = "Repairs all of physical items in my inventory. \nPower Cost : "..TUNING.SPELLMATTER_POWERCOST.."\nSanity Cost : "..TUNING.SPELLMATTER_SANITYCOST

STRINGS.YUKARI_UPGRADE_FINISHED = "Upgrade Finished" 
STRINGS.YUKARI_CURRENT_LEVEL = "Current Level"
STRINGS.YUKARI_NOSKILL = "I don't have any skills."

STRINGS.HEALTH = "Health"
STRINGS.HUNGER = "Hunger"
STRINGS.SANITY = "Sanity"
STRINGS.POWER = "Power"
STRINGS.ABILITY = "ability"
STRINGS.INVINCIBILITY = "Invincibility"
STRINGS.ACTIVATED = "activated"
STRINGS.READY = "ready"
STRINGS.SECONDS = "s"

STRINGS.ACTION_YTELE = "Teleport"
STRINGS.ACTION_CASTTOHO = "Castspell"
STRINGS.ACTION_CASTTOHOH = "Castspell"

STRINGS.CUSTOM_INTRO = {
	"OWWWWWWAAAAAAWWWW!!!!!",
	"HOW THE HECK CAN YOU JUST PASS THROUGH OUR BOUNDARIES?!",
	"Well, whatever you were strong or not,",
	"I will never use your own power!",
	"YOU WILL SUFFER, DEATH WILL FOUND YOU.",
	"BECAUSE OF YOUR GODDAMN WEAKNESS!!"
}

STRINGS.CUSTOM_INTRO_SW = {
	"Who R You",
	"Who R You StranGer", 
	"You Better Out", 
}

if Language == "ch" then

STRINGS.CHARACTER_TITLES.yakumoyukari = "境界的妖怪"
STRINGS.CHARACTER_DESCRIPTIONS.yakumoyukari = "拥 有 自 己 的 能 力 '妖 力'.\n 当 她 从 自 己 的 世 界 中 获 得 ' 力 量 ' 之 后 将 变 得 极 其 可 怕."
STRINGS.CHARACTER_QUOTES.yakumoyukari = "\"我 将 会 掌 控 这 个 世 界！.\""
STRINGS.CHARACTERS.YAKUMOYUKARI = require "speech_yakumoyukari_ch"

STRINGS.NAMES.YUKARIUMBRE = "紫 的 阳 伞"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.YUKARIUMBRE = "可 以 制 造 叫 做 '隙 间'的 东 西"
STRINGS.NAMES.YUKARIHAT = "紫 的 帽 子"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.YUKARIHAT = "好 吧，我 不 认 为 这 帽 子 很 罕 见."
STRINGS.NAMES.TUNNEL = "隙 间 之 所"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.TUNNEL = "连 接 到 其 他 空 间."
STRINGS.NAMES.SCHEME = "隙 间"
STRINGS.TABS.TOUHOU = "东 方"

STRINGS.NAMES.HEALTHPANEL = "生 命 升 级"
STRINGS.RECIPE_DESC.HEALTHPANEL = "升 级 生 命"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHPANEL = "一 大 块 生 命 图 标?"
STRINGS.NAMES.HUNGERPANEL = "饥 饿 升 级"
STRINGS.RECIPE_DESC.HUNGERPANEL = "升 级 饥 饿"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERPANEL = "这 让 我 饿 的 慢 一 点."
STRINGS.NAMES.SANITYPANEL = "心 智 升 级"
STRINGS.RECIPE_DESC.SANITYPANEL = "升 级 心 智"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYPANEL = "额.. 这 上 面 有 个 大 脑."
STRINGS.NAMES.POWERPANEL = "妖 力 升 级"
STRINGS.RECIPE_DESC.POWERPANEL = "升 级 妖 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERPANEL = "这 就 是 我 的 力 量 吗?!"
STRINGS.NAMES.HEALTHULT = "阴 阳 玉"
STRINGS.RECIPE_DESC.HEALTHULT = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHULT = "我 伙 伴 的 力 量"
STRINGS.NAMES.HUNGERULT = "八 卦"
STRINGS.RECIPE_DESC.HUNGERULT = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERULT = "我 感 觉 整 个 世 界 的 力 量 都 在 里 面."
STRINGS.NAMES.SANITYULT = "第 三 只 眼"
STRINGS.RECIPE_DESC.SANITYULT = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYULT = "这 个 眼 睛 洞 察 人 们 的 思 想."
STRINGS.NAMES.POWERULT = "境 界"
STRINGS.RECIPE_DESC.POWERULT = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERULT = "它 让 你 知 道 我 是 谁."
STRINGS.NAMES.HEALTHULTSW = "冈 格 尼 尔 之 枪"
STRINGS.RECIPE_DESC.HEALTHULTSW = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HEALTHULTSW = "我 感 受 不 到 这 里 有 那 么 多 的 力 量，恩!"
STRINGS.NAMES.HUNGERULTSW = "莱 瓦 丁"
STRINGS.RECIPE_DESC.HUNGERULTSW = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.HUNGERULTSW = "这 象 征 着'毁 灭'."
STRINGS.NAMES.SANITYULTSW = "樱 花"
STRINGS.RECIPE_DESC.SANITYULTSW = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SANITYULTSW = "我 的 朋 友 圈."
STRINGS.NAMES.POWERULTSW = "纹 章"
STRINGS.RECIPE_DESC.POWERULTSW = "解 禁 终 极 能 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.POWERULTSW = "它 让 你 知 道 我 是 谁."

STRINGS.NAMES.SPELLCARD_TEST = "测 试"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_TEST = "玩 家 与 制 作 者 之 间 的 境 界. 哈 哈"
STRINGS.NAMES.SPELLCARD_MESH = "光 与 暗 的 网 孔"
STRINGS.RECIPE_DESC.SPELLCARD_MESH = "将 心 智 值 反 转"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_MESH = "反 转 我 的 心 智. 消 耗 : 60"
STRINGS.NAMES.SPELLCARD_AWAY = "八 云 紫 的 神 隐"
STRINGS.RECIPE_DESC.SPELLCARD_AWAY = "使 紫 变 为 隐 形"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_AWAY = "它 可 以 让 我 隐 匿 10 秒. 消 耗 : 50"
STRINGS.NAMES.SPELLCARD_NECRO = "死 亡 幻 想 曲"
STRINGS.RECIPE_DESC.SPELLCARD_NECRO = "将 你 脚 下 的 大 地 变 为 死 亡 之 地"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_NECRO = "让 一 切 死 亡. 消 耗 : 300"
STRINGS.NAMES.SPELLCARD_CURSE = "梦 境 与 现 实 的 诅 咒"
STRINGS.RECIPE_DESC.SPELLCARD_CURSE = "消 耗 心 智 暂 时 提 升 攻 击 力"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_CURSE = "将 心 智 转 化 为 力 量 持 续 20 秒. 消 耗 : 50"
STRINGS.NAMES.SPELLCARD_BALANCE = "动 与 静 的 均 衡"
STRINGS.RECIPE_DESC.SPELLCARD_BALANCE = "使 附 近 植 物 生 长"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BALANCE = "植 物 瞬 间 生 长. 消 耗 : 100"
STRINGS.NAMES.SPELLCARD_LAPLACE = "魔 眼 \"拉 普 拉 斯 之 魔\""
STRINGS.RECIPE_DESC.SPELLCARD_LAPLACE = "用 她 的 眼 睛 观 察 世 界"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_LAPLACE = "用 我 的 眼 睛 观 看 世 界. 消 耗 / 每 秒 : 1"
STRINGS.NAMES.SPELLCARD_BUTTER = "栖 于 禅 寺 的 妖 蝶"
STRINGS.RECIPE_DESC.SPELLCARD_BUTTER = "生 成 蝴 蝶"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BUTTER = "产 生 蝴 蝶. 消 耗 : 50"
STRINGS.NAMES.SPELLCARD_BAIT = "魅 惑 的 诱 饵"
STRINGS.RECIPE_DESC.SPELLCARD_BAIT = " 生 成 保 护 屏 障"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_BAIT = "滋 生 保 护 屏 障，同 时 吸 引 附 近 的 生 物. 消 耗 / 每 秒 : 2"
STRINGS.NAMES.SPELLCARD_ADDICTIVE = "空 饵"
STRINGS.RECIPE_DESC.SPELLCARD_ADDICTIVE = "使 植 物 、 农 场 恢 复 生 长"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_ADDICTIVE = "使 周 围 的 植 物 恢 复 活 力. 消 耗 : 200"
STRINGS.NAMES.SPELLCARD_LAMENT = "后 悔 打 开 的 玉 匣"
STRINGS.RECIPE_DESC.SPELLCARD_LAMENT = "在 身 边 随 机 生 成 物 品"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_LAMENT = "随 机 生 成 物 品. 消 耗 : 20"
STRINGS.NAMES.SPELLCARD_MATTER = "物 质 与 反 物 质 的 宇 宙"
STRINGS.RECIPE_DESC.SPELLCARD_MATTER = "修 复 战 斗 装 备"
STRINGS.CHARACTERS.YAKUMOYUKARI.DESCRIBE.SPELLCARD_MATTER = "修 复 身 上 所 有 的 战 具. 消 耗 : 150"
	
STRINGS.YUKARI_UPGRADE_FINISHED = "升 级 完 成"
STRINGS.YUKARI_CURRENT_LEVEL = "目 前 的 等 级"
STRINGS.YUKARI_NOSKILL = "I don't have any skills."

STRINGS.HEALTH = "生 命"
STRINGS.HUNGER = "饥 饿"
STRINGS.SANITY = "心 智"
STRINGS.POWER = "妖 力"
STRINGS.ABILITY = "能 力"
STRINGS.INVINCIBILITY = "Invincibility"
STRINGS.ACTIVATED = "activated"
STRINGS.READY = "ready"
STRINGS.SECONDS = "seconds"

ACTIONS.UTELEPORT.str = "눈 箇"
ACTIONS.SPAWNG.str = " 냥"
ACTIONS.CASTTOHO.str = "嘉 랬"
ACTIONS.CASTTOHOH.str = "嘉 랬"

STRINGS.CUSTOM_INTRO = {
	"哦 哦 哦 哦 哦 哦 哦 哇 啊 啊 啊 啊 哦 哦!!",
	"你 是 怎 么 打 破 结 界 来 到 这 里 的?!",
	"不 过 没 关 系，无 论 你 以 前 是 否 强 大,",
	"我 刚 让 你 变 得 一 团 糟!",
	"你 不 可 能 活 下 去，你 必 须 死 ！",
	"因 为 你 现 在 很 虚 弱!!",
}

STRINGS.CUSTOM_INTRO_SW = {
	"Who R You",
	"Who R You StranGer", 
	"You Better Out", 
}

end